using FaceFusion.Parity;
using Xunit;

namespace FaceFusion.ParityTests;

/// <summary>
/// Ground truth for these cases was generated by running real `numpy.allclose` (numpy 2.4.6,
/// via python3) on the same inputs; see the values/results recorded in each test's comments.
/// </summary>
public class TensorComparisonTests
{
    [Fact]
    public void SimpleMatch_Passes()
    {
        // numpy: np.allclose([1.0, 2.0, 3.0], [1.0, 2.0, 3.0]) -> True
        var result = TensorComparison.Compare(new double[] { 1.0, 2.0, 3.0 }, new double[] { 1.0, 2.0, 3.0 });
        Assert.True(result.Passed);
        Assert.Equal(0, result.MismatchCount);
        Assert.Equal(3, result.TotalCount);
    }

    [Fact]
    public void SimpleMismatch_Fails()
    {
        // numpy: np.allclose([1.0, 2.0, 5.0], [1.0, 2.0, 3.0]) -> False
        var result = TensorComparison.Compare(new double[] { 1.0, 2.0, 5.0 }, new double[] { 1.0, 2.0, 3.0 });
        Assert.False(result.Passed);
        Assert.Equal(1, result.MismatchCount);
        Assert.Equal(2, result.MaxDifferenceIndex);
        Assert.Equal(2.0, result.MaxAbsoluteDifference, 10);
        Assert.Equal(5.0, result.ActualAtMaxDifference);
        Assert.Equal(3.0, result.ExpectedAtMaxDifference);
    }

    [Fact]
    public void ToleranceBoundary_ExactlyAtThreshold_Passes()
    {
        // numpy ground truth (rtol=1e-5, atol=1e-8, expected=0.0 so threshold==atol exactly,
        // avoiding float rounding from the rtol*expected term):
        //   np.allclose([1e-8], [0.0]) -> True   (diff == atol, "<=" passes)
        var result = TensorComparison.Compare(new double[] { 1e-8 }, new double[] { 0.0 });
        Assert.True(result.Passed);
    }

    [Fact]
    public void ToleranceBoundary_JustOverThreshold_Fails()
    {
        // numpy: np.allclose([1.1e-8], [0.0]) -> False
        var result = TensorComparison.Compare(new double[] { 1.1e-8 }, new double[] { 0.0 });
        Assert.False(result.Passed);
    }

    [Fact]
    public void RtolAsymmetry_UsesExpectedNotActual()
    {
        // numpy ground truth (rtol=0.1, atol=0.0):
        //   np.allclose([1.0], [1.105], rtol=0.1, atol=0.0) -> True
        //   np.allclose([1.105], [1.0], rtol=0.1, atol=0.0) -> False
        // This demonstrates the numpy.allclose asymmetry: the rtol term scales with the
        // *second* argument (expected/ground truth), not the first (actual).
        var forward = TensorComparison.Compare(new double[] { 1.0 }, new double[] { 1.105 }, relativeTolerance: 0.1, absoluteTolerance: 0.0);
        var backward = TensorComparison.Compare(new double[] { 1.105 }, new double[] { 1.0 }, relativeTolerance: 0.1, absoluteTolerance: 0.0);

        Assert.True(forward.Passed);
        Assert.False(backward.Passed);
    }

    [Fact]
    public void NaNVsNaN_DefaultEqualNanFalse_Fails()
    {
        // numpy: np.allclose([np.nan], [np.nan]) -> False (equal_nan defaults to False)
        var result = TensorComparison.Compare(new double[] { double.NaN }, new double[] { double.NaN });
        Assert.False(result.Passed);
    }

    [Fact]
    public void NaNVsNaN_EqualNanTrue_Passes()
    {
        // numpy: np.allclose([np.nan], [np.nan], equal_nan=True) -> True
        var result = TensorComparison.Compare(new double[] { double.NaN }, new double[] { double.NaN }, equalNan: true);
        Assert.True(result.Passed);
    }

    [Fact]
    public void PositiveInfinityVsPositiveInfinity_Passes()
    {
        // numpy: np.allclose([np.inf], [np.inf]) -> True
        var result = TensorComparison.Compare(new double[] { double.PositiveInfinity }, new double[] { double.PositiveInfinity });
        Assert.True(result.Passed);
    }

    [Fact]
    public void PositiveInfinityVsNegativeInfinity_Fails()
    {
        // numpy: np.allclose([np.inf], [-np.inf]) -> False
        var result = TensorComparison.Compare(new double[] { double.PositiveInfinity }, new double[] { double.NegativeInfinity });
        Assert.False(result.Passed);
    }

    [Fact]
    public void EmptyArrays_Pass()
    {
        // numpy: np.allclose([], []) -> True
        var result = TensorComparison.Compare(ReadOnlySpan<double>.Empty, ReadOnlySpan<double>.Empty);
        Assert.True(result.Passed);
        Assert.Equal(0, result.TotalCount);
    }

    [Fact]
    public void ShapeMismatch_IsDistinctFailure_NotException()
    {
        var result = TensorComparison.Compare(new double[] { 1.0, 2.0 }, new double[] { 1.0, 2.0, 3.0 });
        Assert.False(result.Passed);
        Assert.True(result.ShapeMismatch);
        Assert.Equal(2, result.ActualLength);
        Assert.Equal(3, result.ExpectedLength);
        Assert.Contains("shape mismatch", result.Describe(), StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Describe_ReportsMismatchDiagnostics()
    {
        var result = TensorComparison.Compare(new double[] { 1.0, 100.0 }, new double[] { 1.0, 1.0 });
        var description = result.Describe();
        Assert.Contains("FAIL", description);
        Assert.Contains("1/2", description);
    }

    [Fact]
    public void Describe_ReportsPassMessage()
    {
        var result = TensorComparison.Compare(new double[] { 1.0 }, new double[] { 1.0 });
        Assert.Contains("PASS", result.Describe());
    }

    [Fact]
    public void MixedNaNAndFiniteMismatch_CountsBothAsFailures()
    {
        // numpy: np.allclose([np.nan, 5.0], [np.nan, 3.0]) -> False, and both elements
        // individually fail (NaN because equal_nan defaults False, 5.0 vs 3.0 because outside
        // tolerance).
        var result = TensorComparison.Compare(new double[] { double.NaN, 5.0 }, new double[] { double.NaN, 3.0 });
        Assert.False(result.Passed);
        Assert.Equal(2, result.MismatchCount);
    }
}
