<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FaceFusion.Types\FaceFusion.Types.csproj" />
    <ProjectReference Include="..\FaceFusion.Core\FaceFusion.Core.csproj" />
    <ProjectReference Include="..\FaceFusion.Tensors\FaceFusion.Tensors.csproj" />
    <ProjectReference Include="..\FaceFusion.Vision\FaceFusion.Vision.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
