using System.Diagnostics;
using FaceFusion.Cli;

namespace FaceFusion.UnitTests;

/// <summary>
/// Guards the generated CLI option table against drift from <c>facefusion/program.py</c>.
///
/// Every flag appears in job JSON and in user scripts, so a renamed or retyped option is a
/// breaking change rather than a cosmetic one. <c>CliOptions.cs</c> is generated by
/// <c>tools/parity/generate_cli_options.py</c>; this test re-parses the Python and fails
/// if the two have diverged, which is what would happen if someone edited the generated
/// file by hand or upstream added a flag.
/// </summary>
public sealed class CliOptionsTests
{
    /// <summary>
    /// Skips when the Python source or python3 is unavailable — CI has the checkout but
    /// not necessarily the interpreter, and a missing interpreter is not a port defect.
    /// </summary>
    private sealed class PythonSourceFactAttribute : FactAttribute
    {
        public PythonSourceFactAttribute()
        {
            var root = FindRepoRoot();

            if (!File.Exists(Path.Combine(root, "facefusion", "program.py")))
            {
                Skip = "facefusion/program.py not found; run from a full checkout";
            }
            else if (RunPython("print('ok')", string.Empty) is null)
            {
                Skip = "python3 unavailable";
            }
        }
    }

    [Fact]
    public void EveryFlagIsUniqueAndWellFormed()
    {
        Assert.NotEmpty(CliOptions.All);

        var flags = CliOptions.All.Select(option => option.Flag).ToList();
        Assert.Equal(flags.Count, flags.Distinct(StringComparer.Ordinal).Count());

        foreach (var option in CliOptions.All)
        {
            Assert.StartsWith("--", option.Flag, StringComparison.Ordinal);
            // The state key is the flag with dashes turned into underscores; that mapping
            // is what argparse's `dest` does and what the job JSON keys use.
            Assert.Equal(option.Flag[2..].Replace('-', '_'), option.StateKey);
        }
    }

    [PythonSourceFact]
    public void MatchesProgramPy()
    {
        var repoRoot = FindRepoRoot();
        var programPath = Path.Combine(repoRoot, "facefusion", "program.py");

        var script = """
            import re, sys
            source = open(sys.argv[1]).read()
            seen = []
            for match in re.finditer(r"add_argument\(\s*'(--[a-z0-9-]+)'", source):
                flag = match.group(1)
                if flag not in seen:
                    seen.append(flag)
            print("\n".join(seen))
            """;

        var pythonFlags = RunPython(script, programPath);
        Assert.NotNull(pythonFlags);

        var expected = pythonFlags!
            .Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .ToList();
        var actual = CliOptions.All.Select(option => option.Flag).ToList();

        var missing = expected.Except(actual, StringComparer.Ordinal).ToList();
        var extra = actual.Except(expected, StringComparer.Ordinal).ToList();

        Assert.True(
            missing.Count == 0 && extra.Count == 0,
            $"CLI options have drifted from program.py. Missing: [{string.Join(", ", missing)}]. " +
            $"Extra: [{string.Join(", ", extra)}]. Regenerate with " +
            "python3 tools/parity/generate_cli_options.py");
    }

    private static string? RunPython(string script, string argument)
    {
        var scriptPath = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName() + ".py");
        File.WriteAllText(scriptPath, script);

        try
        {
            using var process = Process.Start(new ProcessStartInfo
            {
                FileName = "python3",
                ArgumentList = { scriptPath, argument },
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                WorkingDirectory = FindRepoRoot()
            });

            if (process is null)
            {
                return null;
            }

            var output = process.StandardOutput.ReadToEnd();
            process.WaitForExit();
            return process.ExitCode == 0 ? output : null;
        }
        catch (System.ComponentModel.Win32Exception)
        {
            return null;
        }
        finally
        {
            File.Delete(scriptPath);
        }
    }

    private static string FindRepoRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);

        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "FaceFusion.sln")))
        {
            directory = directory.Parent;
        }

        return directory?.FullName ?? Directory.GetCurrentDirectory();
    }
}
