using System.Diagnostics;
using FaceFusion.Cli;

namespace FaceFusion.UnitTests;

/// <summary>
/// Guards the generated CLI option table against drift from <c>facefusion/program.py</c>.
///
/// Every flag appears in job JSON and in user scripts, so a renamed or retyped option is a
/// breaking change rather than a cosmetic one. <c>CliOptions.cs</c> is generated by
/// <c>tools/parity/generate_cli_options.py</c>; this test re-parses the Python and fails
/// if the two have diverged, which is what would happen if someone edited the generated
/// file by hand or upstream added a flag.
/// </summary>
public sealed class CliOptionsTests
{
    /// <summary>
    /// Skips when the Python source or python3 is unavailable — CI has the checkout but
    /// not necessarily the interpreter, and a missing interpreter is not a port defect.
    /// </summary>
    private sealed class PythonSourceFactAttribute : FactAttribute
    {
        public PythonSourceFactAttribute()
        {
            var root = FindRepoRoot();

            if (!File.Exists(Path.Combine(root, "facefusion", "program.py")))
            {
                Skip = "facefusion/program.py not found; run from a full checkout";
            }
            else if (RunPython("print('ok')", string.Empty) is null)
            {
                Skip = "python3 unavailable";
            }
        }
    }

    [Fact]
    public void EveryFlagIsUniqueAndWellFormed()
    {
        Assert.NotEmpty(CliOptions.All);

        var flags = CliOptions.All.Select(option => option.Flag).ToList();
        Assert.Equal(flags.Count, flags.Distinct(StringComparer.Ordinal).Count());

        foreach (var option in CliOptions.All)
        {
            Assert.StartsWith("--", option.Flag, StringComparison.Ordinal);
            // The state key is the flag with dashes turned into underscores; that mapping
            // is what argparse's `dest` does and what the job JSON keys use.
            Assert.Equal(option.Flag[2..].Replace('-', '_'), option.StateKey);
        }
    }

    /// <summary>
    /// Compares the generated table against the union of every subcommand's real
    /// <c>--help</c> output.
    ///
    /// An earlier version of this test re-parsed <c>program.py</c> with the same regex the
    /// generator used, so when that regex proved wrong — it skipped any option declaring a
    /// short alias first, losing <c>--source-paths</c>, <c>--target-path</c> and
    /// <c>--output-path</c> — the test agreed with the bug instead of catching it. It also
    /// could not see processor options, which each processor registers itself rather than
    /// declaring in <c>program.py</c>. <c>--help</c> is the surface users actually get, so
    /// it cannot share a parsing bug with the generator.
    /// </summary>
    [PythonSourceFact]
    public void MatchesPythonHelpOutput()
    {
        var script = """
            import re, subprocess, sys
            commands = sys.argv[1:]
            flags = set()
            for command in commands:
                result = subprocess.run(['python3', 'facefusion.py', command, '--help'],
                    capture_output=True, text=True, timeout=300)
                flags |= set(re.findall(r'--[a-z0-9-]+', result.stdout))
            flags.discard('--help')
            print("\n".join(sorted(flags)))
            """;

        var commands = string.Join(" ", CliCommands.FlagsByCommand.Keys);
        var pythonFlags = RunPython(script, commands);
        Assert.NotNull(pythonFlags);

        var expected = pythonFlags!
            .Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .ToList();
        var actual = CliOptions.All.Select(option => option.Flag).ToList();

        var missing = expected.Except(actual, StringComparer.Ordinal).ToList();

        // Only "missing" fails the build. The C# table is the union across every
        // subcommand, so a flag Python shows on a command not enumerated here would look
        // "extra" without being wrong; CliCommands is what pins per-command membership.
        Assert.True(
            missing.Count == 0,
            $"CLI options have drifted from the Python CLI. Missing: [{string.Join(", ", missing)}]. " +
            "Regenerate with python3 tools/parity/generate_cli_options.py");
    }

    /// <summary>
    /// Every command's flag set must be a subset of the known options, so a command cannot
    /// reference a flag the table does not define.
    /// </summary>
    [Fact]
    public void EveryCommandFlagIsADefinedOption()
    {
        var defined = CliOptions.All.Select(option => option.Flag).ToHashSet(StringComparer.Ordinal);

        foreach (var (command, flags) in CliCommands.FlagsByCommand)
        {
            foreach (var flag in flags)
            {
                Assert.True(defined.Contains(flag), $"{command} references undefined option {flag}");
            }
        }
    }

    private static string? RunPython(string script, string arguments)
    {
        var scriptPath = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName() + ".py");
        File.WriteAllText(scriptPath, script);

        try
        {
            var startInfo = new ProcessStartInfo
            {
                FileName = "python3",
                ArgumentList = { scriptPath },
                // Split on spaces: every value passed here is a command name.
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                WorkingDirectory = FindRepoRoot()
            };

            foreach (var argument in arguments.Split(' ', StringSplitOptions.RemoveEmptyEntries))
            {
                startInfo.ArgumentList.Add(argument);
            }

            using var process = Process.Start(startInfo);

            if (process is null)
            {
                return null;
            }

            var output = process.StandardOutput.ReadToEnd();
            process.WaitForExit();
            return process.ExitCode == 0 ? output : null;
        }
        catch (System.ComponentModel.Win32Exception)
        {
            return null;
        }
        finally
        {
            File.Delete(scriptPath);
        }
    }

    private static string FindRepoRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);

        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "FaceFusion.sln")))
        {
            directory = directory.Parent;
        }

        return directory?.FullName ?? Directory.GetCurrentDirectory();
    }
}
