using FaceFusion.Face;
using FaceFusion.Types;
using OpenCvSharp;

namespace FaceFusion.UnitTests;

/// <summary>
/// Port of the ground-truth checks for <c>facefusion/face_helper.py</c>. There is no
/// <c>tests/test_face_helper.py</c> in the Python suite, so all expected values below were
/// generated by running the actual Python implementation.
///
/// <para>
/// <b>Ground-truth provenance — read this before trusting a number below.</b>
/// </para>
/// <para>
/// <b>Real numpy-verified ground truth</b> (transcribed <c>facefusion/face_helper.py</c> run
/// under real Python 3 + numpy 2.4.6, no cv2 involved): <c>CreateStaticAnchors</c>,
/// <c>DistanceToBoundingBox</c>, <c>DistanceToFaceLandmark5</c>, <c>ScaleFaceLandmark5</c>,
/// <c>ConvertToFaceLandmark5</c>, <c>EstimateFaceAngle</c>, <c>GetNmsThreshold</c>,
/// <c>CreateBoundingBox</c>, <c>NormalizeBoundingBox</c>, <c>CalculateBoundingBoxOverlap</c>,
/// <c>AveragePoints</c>.
/// </para>
/// <para>
/// <b>Real cv2-verified ground truth</b> (the environment was upgraded mid-task to
/// opencv-python-headless 5.0.0; the same transcribed Python module was run for real, calling
/// actual <c>cv2.estimateAffinePartial2D</c> / <c>cv2.warpAffine</c> / <c>cv2.getAffineTransform</c>
/// / <c>cv2.invertAffineTransform</c> / <c>cv2.transform</c> / <c>cv2.getRotationMatrix2D</c> /
/// <c>cv2.dnn.NMSBoxes</c>): <c>EstimateMatrixByFaceLandmark5</c>, <c>WarpFaceByFaceLandmark5</c>,
/// <c>WarpFaceByBoundingBox</c>, <c>WarpFaceByTranslation</c>, <c>CalculatePasteArea</c> (including
/// the int32-rounding quirk documented on <see cref="FaceHelper.CalculatePasteArea"/>),
/// <c>PasteBack</c>, <c>CreateRotationMatrixAndSize</c>, <c>MergeMatrix</c>, <c>ApplyNms</c>. These
/// compare against a tolerance (matrix values: 1e-4 absolute; warped-pixel sums: within 2000
/// out of a several-million total, via <see cref="AssertPixelSumClose"/>; corner pixels that
/// land exactly on an un-interpolated source pixel: exact) rather than bit-for-bit, because the
/// C# side runs against OpenCvSharp4 4.13's native OpenCV build while the ground truth ran
/// against opencv-python-headless 5.0.0's — two different builds of the same algorithm that
/// resolve INTER_AREA/INTER_LINEAR sub-pixel sampling with tiny rounding differences at some
/// pixels, but close enough that a wrong flag, transposed matrix, or dtype-promotion bug would
/// fail the tolerance immediately (which is the point of these tests).
/// </para>
/// <para>
/// <b>Property-only (no Python ground truth)</b>: none — every function in scope got either
/// numpy or cv2 ground truth once cv2 became available in this environment. A few tests below
/// additionally check structural properties (invertibility, warp-then-unwarp round trip) as a
/// second, independent line of defense on top of the ground-truth comparison, not as a
/// substitute for it.
/// </para>
/// </summary>
public sealed class FaceHelperTests
{
    private const double MatrixTolerance = 1e-4;

    // -----------------------------------------------------------------
    // WARP_TEMPLATE_SET
    // -----------------------------------------------------------------

    [Fact]
    public void GetWarpTemplate_Arcface112V1_MatchesPythonLiteralsExactly()
    {
        var template = FaceHelper.GetWarpTemplate(WarpTemplate.Arcface112V1);

        Assert.Equal(0.35473214, template[0, 0], 8);
        Assert.Equal(0.45658929, template[0, 1], 8);
        Assert.Equal(0.64526786, template[1, 0], 8);
        Assert.Equal(0.45658929, template[1, 1], 8);
        Assert.Equal(0.50000000, template[2, 0], 8);
        Assert.Equal(0.61154464, template[2, 1], 8);
        Assert.Equal(0.37913393, template[3, 0], 8);
        Assert.Equal(0.77687500, template[3, 1], 8);
        Assert.Equal(0.62086607, template[4, 0], 8);
        Assert.Equal(0.77687500, template[4, 1], 8);
    }

    [Fact]
    public void GetWarpTemplate_Ffhq512_MatchesPythonLiteralsExactly()
    {
        var template = FaceHelper.GetWarpTemplate(WarpTemplate.Ffhq512);

        Assert.Equal(0.37691676, template[0, 0], 8);
        Assert.Equal(0.46864664, template[0, 1], 8);
        Assert.Equal(0.61150205, template[4, 0], 8);
        Assert.Equal(0.72490465, template[4, 1], 8);
    }

    [Fact]
    public void GetWarpTemplate_ReturnsDefensiveCopy()
    {
        var first = FaceHelper.GetWarpTemplate(WarpTemplate.Arcface128);
        first[0, 0] = -999;
        var second = FaceHelper.GetWarpTemplate(WarpTemplate.Arcface128);

        Assert.Equal(0.36167656, second[0, 0], 8);
    }

    // -----------------------------------------------------------------
    // create_static_anchors — numpy ground truth
    // -----------------------------------------------------------------

    [Fact]
    public void CreateStaticAnchors_Stride8Total2_MatchesNumpy()
    {
        var anchors = FaceHelper.CreateStaticAnchors(8, 2, 3, 4);

        Assert.Equal(24, anchors.GetLength(0));

        float[,] expected =
        {
            { 0, 0 }, { 0, 0 }, { 8, 0 }, { 8, 0 }, { 16, 0 }, { 16, 0 },
            { 0, 8 }, { 0, 8 }, { 8, 8 }, { 8, 8 }, { 16, 8 }, { 16, 8 },
            { 0, 16 }, { 0, 16 }, { 8, 16 }, { 8, 16 }, { 16, 16 }, { 16, 16 },
            { 0, 24 }, { 0, 24 }, { 8, 24 }, { 8, 24 }, { 16, 24 }, { 16, 24 },
        };

        for (var i = 0; i < 24; i++)
        {
            Assert.Equal(expected[i, 0], anchors[i, 0]);
            Assert.Equal(expected[i, 1], anchors[i, 1]);
        }
    }

    [Fact]
    public void CreateStaticAnchors_Stride16Total3_MatchesNumpy()
    {
        var anchors = FaceHelper.CreateStaticAnchors(16, 3, 2, 2);

        float[,] expected =
        {
            { 0, 0 }, { 0, 0 }, { 0, 0 },
            { 16, 0 }, { 16, 0 }, { 16, 0 },
            { 0, 16 }, { 0, 16 }, { 0, 16 },
            { 16, 16 }, { 16, 16 }, { 16, 16 },
        };

        Assert.Equal(12, anchors.GetLength(0));
        for (var i = 0; i < 12; i++)
        {
            Assert.Equal(expected[i, 0], anchors[i, 0]);
            Assert.Equal(expected[i, 1], anchors[i, 1]);
        }
    }

    [Fact]
    public void CreateStaticAnchors_CachedCall_ReturnsIndependentCopy()
    {
        var first = FaceHelper.CreateStaticAnchors(8, 2, 3, 4);
        first[0, 0] = -1;
        var second = FaceHelper.CreateStaticAnchors(8, 2, 3, 4);

        Assert.Equal(0, second[0, 0]);
    }

    // -----------------------------------------------------------------
    // distance_to_bounding_box / distance_to_face_landmark_5 — numpy ground truth
    // -----------------------------------------------------------------

    [Fact]
    public void DistanceToBoundingBox_MatchesNumpy()
    {
        var points = new float[,] { { 10f, 20f }, { 30f, 40f } };
        var distance = new float[,] { { 1f, 2f, 3f, 4f }, { 5f, 6f, 7f, 8f } };

        var result = FaceHelper.DistanceToBoundingBox(points, distance);

        Assert.Equal(new[] { 9f, 18f, 13f, 24f }, new[] { result[0, 0], result[0, 1], result[0, 2], result[0, 3] });
        Assert.Equal(new[] { 25f, 34f, 37f, 48f }, new[] { result[1, 0], result[1, 1], result[1, 2], result[1, 3] });
    }

    [Fact]
    public void DistanceToFaceLandmark5_MatchesNumpy()
    {
        var points = new float[,] { { 100f, 200f } };
        var distance = new float[,] { { 1f, 2f, 3f, 4f, 5f, 6f, 7f, 8f, 9f, 10f } };

        var result = FaceHelper.DistanceToFaceLandmark5(points, distance);

        Assert.Equal(101f, result[0, 0, 0]);
        Assert.Equal(202f, result[0, 0, 1]);
        Assert.Equal(103f, result[0, 1, 0]);
        Assert.Equal(204f, result[0, 1, 1]);
        Assert.Equal(105f, result[0, 2, 0]);
        Assert.Equal(206f, result[0, 2, 1]);
        Assert.Equal(107f, result[0, 3, 0]);
        Assert.Equal(208f, result[0, 3, 1]);
        Assert.Equal(109f, result[0, 4, 0]);
        Assert.Equal(210f, result[0, 4, 1]);
    }

    // -----------------------------------------------------------------
    // scale_face_landmark_5 / convert_to_face_landmark_5 — numpy ground truth
    // -----------------------------------------------------------------

    [Fact]
    public void ScaleFaceLandmark5_MatchesNumpy()
    {
        var landmark5 = new float[,]
        {
            { 10f, 20f }, { 30f, 20f }, { 20f, 30f }, { 15f, 40f }, { 25f, 40f },
        };

        var result = FaceHelper.ScaleFaceLandmark5(landmark5, 1.5);

        float[,] expected =
        {
            { 5f, 15f }, { 35f, 15f }, { 20f, 30f }, { 12.5f, 45f }, { 27.5f, 45f },
        };

        for (var i = 0; i < 5; i++)
        {
            Assert.Equal((double)expected[i, 0], (double)result[i, 0], precision: 4);
            Assert.Equal((double)expected[i, 1], (double)result[i, 1], precision: 4);
        }
    }

    [Fact]
    public void ConvertToFaceLandmark5_MatchesNumpy()
    {
        var landmark68 = new float[68, 2];
        for (var i = 0; i < 68; i++)
        {
            for (var c = 0; c < 2; c++)
            {
                landmark68[i, c] = ((i * 2) + c) * 0.37f + 1.1f;
            }
        }

        var result = FaceHelper.ConvertToFaceLandmark5(landmark68);

        // Python ground truth (numpy.mean over rows 36:42 / 42:48, then landmark68[30], [48], [54]).
        Assert.Equal((double)29.590002f, (double)result[0, 0], precision: 3);
        Assert.Equal((double)29.960001f, (double)result[0, 1], precision: 3);
        Assert.Equal((double)34.029999f, (double)result[1, 0], precision: 3);
        Assert.Equal((double)34.400002f, (double)result[1, 1], precision: 3);
        Assert.Equal(landmark68[30, 0], result[2, 0]);
        Assert.Equal(landmark68[30, 1], result[2, 1]);
        Assert.Equal(landmark68[48, 0], result[3, 0]);
        Assert.Equal(landmark68[48, 1], result[3, 1]);
        Assert.Equal(landmark68[54, 0], result[4, 0]);
        Assert.Equal(landmark68[54, 1], result[4, 1]);
    }

    // -----------------------------------------------------------------
    // estimate_face_angle — numpy ground truth
    // -----------------------------------------------------------------

    [Theory]
    [InlineData(0, 0, 100, 0, 0)]
    [InlineData(0, 0, 100, 100, 0)]
    [InlineData(0, 0, 0, 100, 90)]
    [InlineData(0, 0, -100, 0, 180)]
    [InlineData(0, 0, -100, -100, 180)]
    [InlineData(0, 0, -50, 50, 90)]
    [InlineData(0, 0, 10, -100, 270)]
    public void EstimateFaceAngle_MatchesNumpy(float x1, float y1, float x2, float y2, int expectedAngle)
    {
        var landmark68 = new float[68, 2];
        landmark68[0, 0] = x1;
        landmark68[0, 1] = y1;
        landmark68[16, 0] = x2;
        landmark68[16, 1] = y2;

        Assert.Equal(expectedAngle, FaceHelper.EstimateFaceAngle(landmark68));
    }

    // -----------------------------------------------------------------
    // get_nms_threshold — numpy/pure-Python ground truth
    // -----------------------------------------------------------------

    [Theory]
    [InlineData(FaceDetectorModel.Many, new int[] { }, 0.1f)]
    [InlineData(FaceDetectorModel.Scrfd, new[] { 0 }, 0.4f)]
    [InlineData(FaceDetectorModel.Scrfd, new[] { 0, 90 }, 0.3f)]
    [InlineData(FaceDetectorModel.Scrfd, new[] { 0, 90, 180 }, 0.2f)]
    [InlineData(FaceDetectorModel.Scrfd, new[] { 0, 90, 180, 270 }, 0.1f)]
    [InlineData(FaceDetectorModel.Scrfd, new[] { 0, 90, 180, 270, 300 }, 0.4f)]
    public void GetNmsThreshold_MatchesPython(FaceDetectorModel model, int[] angles, float expected)
    {
        Assert.Equal(expected, FaceHelper.GetNmsThreshold(model, angles));
    }

    // -----------------------------------------------------------------
    // create_bounding_box / normalize_bounding_box / overlap / average_points — numpy ground truth
    // -----------------------------------------------------------------

    [Fact]
    public void CreateBoundingBox_MatchesNumpy()
    {
        // 68x2 seeded with numpy.random.RandomState(1).rand(68,2)*300 in the Python reference.
        var random = new Random(0);
        var landmark68 = new float[68, 2];
        var rows = PythonRandomState1Rows();
        for (var i = 0; i < 68; i++)
        {
            landmark68[i, 0] = rows[i, 0];
            landmark68[i, 1] = rows[i, 1];
        }

        var result = FaceHelper.CreateBoundingBox(landmark68);

        Assert.Equal((double)0.03431244567036629f, (double)result[0], precision: 4);
        Assert.Equal((double)5.594186782836914f, (double)result[1], precision: 4);
        Assert.Equal((double)296.6583251953125f, (double)result[2], precision: 2);
        Assert.Equal((double)299.1968688964844f, (double)result[3], precision: 2);
    }

    [Fact]
    public void NormalizeBoundingBox_SwapsOutOfOrderCorners()
    {
        var result = FaceHelper.NormalizeBoundingBox(new[] { 50f, 10f, 5f, 100f });

        Assert.Equal(new[] { 5f, 10f, 50f, 100f }, result);
    }

    [Fact]
    public void CalculateBoundingBoxOverlap_OverlappingBoxes_MatchesNumpy()
    {
        var overlap = FaceHelper.CalculateBoundingBoxOverlap(
            new float[] { 0, 0, 10, 10 }, new float[] { 5, 5, 15, 15 });

        Assert.Equal(0.1428571492433548, overlap, 6);
    }

    [Fact]
    public void CalculateBoundingBoxOverlap_DisjointBoxes_ReturnsZero()
    {
        var overlap = FaceHelper.CalculateBoundingBoxOverlap(
            new float[] { 0, 0, 10, 10 }, new float[] { 20, 20, 30, 30 });

        Assert.Equal(0.0, overlap);
    }

    [Fact]
    public void AveragePoints_MatchesNumpy()
    {
        var previous = new float[,] { { 1f, 2f }, { 3f, 4f } };
        var next = new float[,] { { 5f, 6f }, { 7f, 8f } };

        var result = FaceHelper.AveragePoints(previous, next, 0.25);

        Assert.Equal(2f, result[0, 0]);
        Assert.Equal(3f, result[0, 1]);
        Assert.Equal(4f, result[1, 0]);
        Assert.Equal(5f, result[1, 1]);
    }

    /// <summary>
    /// The exact 68x2 float32 values produced by
    /// <c>numpy.random.RandomState(1).rand(68, 2).astype(numpy.float32) * 300</c> in the Python
    /// reference script, needed verbatim (not merely "some deterministic sequence") because the
    /// expected bounding box in <see cref="CreateBoundingBox_MatchesNumpy"/> is Python's actual
    /// numpy-generated ground truth, not derived from any C# random source.
    /// </summary>
    private static float[,] PythonRandomState1Rows()
    {
        float[] flat =
        {
            125.10659790039062f, 216.09735107421875f, 0.03431244567036629f, 90.69977569580078f,
            44.02676773071289f, 27.70157814025879f, 55.8780632019043f, 103.66822052001953f,
            119.03024291992188f, 161.64501953125f, 125.75835418701172f, 205.56585693359375f,
            61.33567428588867f, 263.43524169921875f, 8.216278076171875f, 201.14024353027344f,
            125.19144439697266f, 167.60694885253906f, 42.11608123779297f, 59.43044662475586f,
            240.22337341308594f, 290.4784851074219f, 94.02725219726562f, 207.69677734375f,
            262.916748046875f, 268.3819885253906f, 25.513263702392578f, 11.716435432434082f,
            50.949127197265625f, 263.4427490234375f, 29.504051208496094f, 126.33228302001953f,
            287.36688232421875f, 159.9495849609375f, 207.56314086914062f, 94.65469360351562f,
            205.9502716064453f, 250.3876953125f, 5.486483097076416f, 225.0432891845703f,
            296.6583251953125f, 224.44970703125f, 84.1332015991211f, 236.78379821777344f,
            30.967802047729492f, 134.36805725097656f, 272.5786437988281f, 88.08424377441406f,
            86.33260345458984f, 39.00857162475586f, 5.810087203979492f, 203.65065002441406f,
            63.488433837890625f, 79.66399383544922f, 147.47193908691406f, 16.008764266967773f,
            172.2352752685547f, 44.01857376098633f, 176.79165649414062f, 209.92750549316406f,
            30.700328826904297f, 124.21678924560547f, 208.32003784179688f, 124.25377655029297f,
            14.986038208007812f, 160.7689208984375f, 199.13839721679688f, 154.46673583984375f,
            283.37841796875f, 175.96652221679688f, 271.02056884765625f, 41.242408752441406f,
            41.782901763916016f, 242.21739196777344f, 119.30304718017578f, 49.606258392333984f,
            278.2525634765625f, 104.32975769042969f, 225.24363708496094f, 217.7993927001953f,
            264.9918212890625f, 187.10165405273438f, 225.28273010253906f, 104.66950225830078f,
            80.97836303710938f, 268.765869140625f, 128.42735290527344f, 289.4520263671875f,
            199.03244018554688f, 186.5087127685547f, 34.42379379272461f, 284.8467712402344f,
            134.9736328125f, 173.51687622070312f, 122.44104766845703f, 71.10809326171875f,
            271.01385498046875f, 172.10385131835938f, 0.8610981106758118f, 185.1434783935547f,
            97.99346923828125f, 158.117431640625f, 265.7826232910156f, 107.1809310913086f,
            272.560546875f, 187.00802612304688f, 4.746372699737549f, 278.8311767578125f,
            207.26907348632812f, 299.1968688964844f, 51.702152252197266f, 41.140724182128906f,
            279.7786560058594f, 209.0454559326172f, 19.800050735473633f, 226.638916015625f,
            226.16285705566406f, 276.9073486328125f, 213.45742797851562f, 37.281288146972656f,
            5.964040279388428f, 7.863296031951904f, 8.49194622039795f, 73.86331939697266f,
            258.0083923339844f, 161.64932250976562f, 165.8466033935547f, 252.60926818847656f,
            37.25199508666992f, 83.7551040649414f, 175.727783203125f, 290.87872314453125f,
            168.30906677246094f, 5.594186782836914f, 240.18980407714844f, 69.89228057861328f,
        };

        var result = new float[68, 2];
        for (var i = 0; i < 68; i++)
        {
            result[i, 0] = flat[i * 2];
            result[i, 1] = flat[(i * 2) + 1];
        }

        return result;
    }

    // -----------------------------------------------------------------
    // apply_nms — real cv2.dnn.NMSBoxes ground truth
    // -----------------------------------------------------------------

    [Fact]
    public void ApplyNms_SuppressesOverlappingBox_MatchesPythonCv2()
    {
        var boxes = new[]
        {
            new float[] { 10, 10, 50, 50 },
            new float[] { 12, 12, 52, 52 },
            new float[] { 200, 200, 260, 260 },
        };
        var scores = new[] { 0.9f, 0.8f, 0.95f };

        var kept = FaceHelper.ApplyNms(boxes, scores, 0.5f, 0.4f);

        // Python: cv2.dnn.NMSBoxes(...) -> [2, 0] (highest-score box first, then the next
        // non-suppressed box in score order).
        Assert.Equal(new[] { 2, 0 }, kept);
    }

    [Fact]
    public void ApplyNms_FourBoxes_MatchesPythonCv2()
    {
        var boxes = new[]
        {
            new float[] { 0, 0, 10, 10 },
            new float[] { 1, 1, 11, 11 },
            new float[] { 50, 50, 60, 60 },
            new float[] { 2, 2, 12, 12 },
        };
        var scores = new[] { 0.5f, 0.6f, 0.7f, 0.55f };

        var kept = FaceHelper.ApplyNms(boxes, scores, 0.0f, 0.3f);

        Assert.Equal(new[] { 2, 1 }, kept);
    }

    // -----------------------------------------------------------------
    // estimate_matrix_by_face_landmark_5 / warp_face_by_* — real cv2 ground truth
    // -----------------------------------------------------------------

    private static readonly float[,] SampleLandmark5 =
    {
        { 38.2f, 51.6f }, { 73.4f, 51.1f }, { 56.0f, 68.9f }, { 42.5f, 87.0f }, { 69.6f, 86.5f },
    };

    [Fact]
    public void EstimateMatrixByFaceLandmark5_Arcface112V2_MatchesPythonCv2()
    {
        using var matrix = FaceHelper.EstimateMatrixByFaceLandmark5(SampleLandmark5, WarpTemplate.Arcface112V2, new Size(112, 112));

        Assert.Equal(1.0963318686687598, matrix.At<double>(0, 0), MatrixTolerance);
        Assert.Equal(-0.00563857966825305, matrix.At<double>(0, 1), MatrixTolerance);
        Assert.Equal(-4.9134707279882175, matrix.At<double>(0, 2), MatrixTolerance);
        Assert.Equal(0.00563857966825305, matrix.At<double>(1, 0), MatrixTolerance);
        Assert.Equal(1.0963318686687598, matrix.At<double>(1, 1), MatrixTolerance);
        Assert.Equal(-4.083465980156119, matrix.At<double>(1, 2), MatrixTolerance);
    }

    [Fact]
    public void EstimateMatrixByFaceLandmark5_Ffhq512_MatchesPythonCv2()
    {
        using var matrix = FaceHelper.EstimateMatrixByFaceLandmark5(SampleLandmark5, WarpTemplate.Ffhq512, new Size(512, 512));

        Assert.Equal(3.738762109438293, matrix.At<double>(0, 0), MatrixTolerance);
        Assert.Equal(-0.02228612497608485, matrix.At<double>(0, 1), MatrixTolerance);
        Assert.Equal(48.96554182160578, matrix.At<double>(0, 2), MatrixTolerance);
        Assert.Equal(0.02228612497608485, matrix.At<double>(1, 0), MatrixTolerance);
        Assert.Equal(3.738762109438293, matrix.At<double>(1, 1), MatrixTolerance);
        Assert.Equal(48.048284047427636, matrix.At<double>(1, 2), MatrixTolerance);
    }

    private static Mat CreateGradientFrame()
    {
        var frame = new Mat(200, 200, MatType.CV_8UC3);
        for (var r = 0; r < 200; r++)
        {
            for (var c = 0; c < 200; c++)
            {
                frame.Set(r, c, new Vec3b((byte)(c % 256), (byte)(r % 256), (byte)((r + c) % 256)));
            }
        }

        return frame;
    }

    [Fact]
    public void WarpFaceByFaceLandmark5_MatchesPythonCv2()
    {
        using var frame = CreateGradientFrame();
        var (crop, matrix) = FaceHelper.WarpFaceByFaceLandmark5(frame, SampleLandmark5, WarpTemplate.Arcface112V1, new Size(112, 112));
        using var _crop = crop;
        using var _matrix = matrix;

        Assert.Equal(112, crop.Rows);
        Assert.Equal(112, crop.Cols);

        Assert.Equal(0.9862849109394941, matrix.At<double>(0, 0), MatrixTolerance);
        Assert.Equal(-0.010640218349153914, matrix.At<double>(0, 1), MatrixTolerance);
        Assert.Equal(1.5616098738140922, matrix.At<double>(0, 2), MatrixTolerance);

        // Python ground truth pixel values (int32 BGR) at the four corners and the centre.
        AssertPixel(crop, 0, 0, 0, 0, 0);
        AssertPixel(crop, 0, 111, 111, 0, 111);
        AssertPixel(crop, 111, 0, 0, 112, 112);
        AssertPixel(crop, 111, 111, 112, 111, 223);
        AssertPixel(crop, 56, 56, 56, 56, 112);

        AssertPixelSumClose(2777355, SumPixels(crop));
    }

    [Fact]
    public void WarpFaceByBoundingBox_LargeBox_UsesAreaInterpolation_MatchesPythonCv2()
    {
        using var frame = CreateGradientFrame();
        var boundingBox = new float[] { 20, 30, 150, 160 };
        var (crop, matrix) = FaceHelper.WarpFaceByBoundingBox(frame, boundingBox, new Size(128, 128));
        using var _crop = crop;
        using var _matrix = matrix;

        Assert.Equal(128, crop.Rows);
        Assert.Equal(128, crop.Cols);
        Assert.Equal(0.9846153846153846, matrix.At<double>(0, 0), MatrixTolerance);
        Assert.Equal(-19.69230769230769, matrix.At<double>(0, 2), MatrixTolerance);
        Assert.Equal(0.9846153846153846, matrix.At<double>(1, 1), MatrixTolerance);
        Assert.Equal(-29.538461538461533, matrix.At<double>(1, 2), MatrixTolerance);

        AssertPixel(crop, 0, 0, 20, 30, 50);
        AssertPixel(crop, 0, 127, 149, 30, 179);
        AssertPixel(crop, 127, 0, 20, 159, 179);
        AssertPixel(crop, 127, 127, 149, 159, 52);

        AssertPixelSumClose(5510011, SumPixels(crop));
    }

    [Fact]
    public void WarpFaceByBoundingBox_SmallBox_UsesLinearInterpolation_MatchesPythonCv2()
    {
        using var frame = CreateGradientFrame();
        var boundingBox = new float[] { 10, 10, 40, 40 };
        var (crop, matrix) = FaceHelper.WarpFaceByBoundingBox(frame, boundingBox, new Size(128, 128));
        using var _crop = crop;
        using var _matrix = matrix;

        Assert.Equal(4.2666666666666675, matrix.At<double>(0, 0), MatrixTolerance);
        Assert.Equal(-42.66666666666667, matrix.At<double>(0, 2), MatrixTolerance);

        AssertPixelSumClose(1630720, SumPixels(crop));
    }

    [Fact]
    public void WarpFaceByTranslation_MatchesPythonCv2()
    {
        using var frame = CreateGradientFrame();
        var (crop, matrix) = FaceHelper.WarpFaceByTranslation(frame, new double[] { 15.5, -8.25 }, 1.75, new Size(100, 90));
        using var _crop = crop;
        using var _matrix = matrix;

        Assert.Equal(90, crop.Rows);
        Assert.Equal(100, crop.Cols);

        Assert.Equal(1.75, matrix.At<double>(0, 0), MatrixTolerance);
        Assert.Equal(0.0, matrix.At<double>(0, 1), MatrixTolerance);
        Assert.Equal(15.5, matrix.At<double>(0, 2), MatrixTolerance);
        Assert.Equal(0.0, matrix.At<double>(1, 0), MatrixTolerance);
        Assert.Equal(1.75, matrix.At<double>(1, 1), MatrixTolerance);
        Assert.Equal(-8.25, matrix.At<double>(1, 2), MatrixTolerance);

        AssertPixel(crop, 0, 0, 0, 0, 0);
        AssertPixel(crop, 0, 99, 48, 5, 52);
        AssertPixel(crop, 89, 0, 0, 0, 0);
        AssertPixel(crop, 89, 99, 48, 56, 103);

        AssertPixelSumClose(823302, SumPixels(crop));
    }

    private static void AssertPixel(Mat frame, int row, int col, byte b, byte g, byte r, int tolerance = 0)
    {
        var pixel = frame.At<Vec3b>(row, col);
        Assert.True(Math.Abs(pixel.Item0 - b) <= tolerance, $"B channel at ({row},{col}): expected {b}, got {pixel.Item0}.");
        Assert.True(Math.Abs(pixel.Item1 - g) <= tolerance, $"G channel at ({row},{col}): expected {g}, got {pixel.Item1}.");
        Assert.True(Math.Abs(pixel.Item2 - r) <= tolerance, $"R channel at ({row},{col}): expected {r}, got {pixel.Item2}.");
    }

    private static long SumPixels(Mat frame)
    {
        long sum = 0;
        for (var r = 0; r < frame.Rows; r++)
        {
            for (var c = 0; c < frame.Cols; c++)
            {
                var pixel = frame.At<Vec3b>(r, c);
                sum += pixel.Item0 + pixel.Item1 + pixel.Item2;
            }
        }

        return sum;
    }

    /// <summary>
    /// Compares a summed-pixel-value ground truth against the C# result within a small
    /// tolerance rather than exactly. <see cref="SumPixels"/> totals can differ by roughly
    /// 0.01-0.1% between the OpenCvSharp4 4.13 native OpenCV build used here and the
    /// opencv-python-headless 5.0.0 build used to generate the ground truth — the same
    /// algorithm and flags, but two different native builds resolve INTER_AREA/INTER_LINEAR
    /// sub-pixel sampling with tiny rounding differences at some pixels. The corner-pixel
    /// assertions alongside these checks (which land exactly on un-interpolated source pixels)
    /// are exact; this tolerance only covers the aggregate, interpolation-sensitive sum.
    /// </summary>
    private static void AssertPixelSumClose(long expected, long actual)
    {
        var delta = Math.Abs(expected - actual);
        Assert.True(delta <= 2000, $"Pixel sum {actual} too far from Python ground truth {expected} (delta {delta}).");
    }

    // -----------------------------------------------------------------
    // calculate_paste_area — real cv2 ground truth, including the int32-rounding quirk
    // -----------------------------------------------------------------

    [Fact]
    public void CalculatePasteArea_MatchesPythonCv2IncludingIntRoundingQuirk()
    {
        using var temp = new Mat(300, 400, MatType.CV_8UC3, Scalar.Black);
        using var crop = new Mat(112, 112, MatType.CV_8UC3, Scalar.Black);
        using var affine = FaceHelper.EstimateMatrixByFaceLandmark5(SampleLandmark5, WarpTemplate.Arcface112V1, new Size(112, 112));

        var (pasteBoundingBox, pasteMatrix) = FaceHelper.CalculatePasteArea(temp, crop, affine);
        using var _pasteMatrix = pasteMatrix;

        // Python ground truth: paste_bounding_box = [0, 0, 113, 113] (the int32-rounded corner
        // transform, not the float64 floor/ceil the Python source's own operators suggest).
        Assert.Equal(new[] { 0, 0, 113, 113 }, pasteBoundingBox);

        Assert.Equal(1.0137878189591465, pasteMatrix.At<double>(0, 0), MatrixTolerance);
        Assert.Equal(0.010936924649047568, pasteMatrix.At<double>(0, 1), MatrixTolerance);
        Assert.Equal(-1.5863040477746504, pasteMatrix.At<double>(0, 2), MatrixTolerance);
        Assert.Equal(-0.010936924649047568, pasteMatrix.At<double>(1, 0), MatrixTolerance);
        Assert.Equal(1.0137878189591465, pasteMatrix.At<double>(1, 1), MatrixTolerance);
        Assert.Equal(-0.276110186077294, pasteMatrix.At<double>(1, 2), MatrixTolerance);
    }

    /// <summary>
    /// Directly proves the int32-rounding quirk described on
    /// <see cref="FaceHelper.CalculatePasteArea"/>: verified independently against a raw
    /// <c>cv2.transform</c> call in Python (not routed through <c>face_helper</c>) with values
    /// chosen so at least one coordinate lands exactly on a rounding tie (2.5 -&gt; 2, ties to
    /// even).
    /// </summary>
    [Fact]
    public void CalculatePasteArea_CornerRounding_IsTiesToEven()
    {
        // A crop frame that maps, via a pure-translation affine matrix, to fractional temp
        // coordinates including an exact .5 tie, so the corner-rounding behaviour is pinned
        // down precisely rather than merely "close to" the float value.
        using var temp = new Mat(50, 50, MatType.CV_8UC3, Scalar.Black);
        using var crop = new Mat(1, 1, MatType.CV_8UC3, Scalar.Black); // corners: (0,0) and (1,1)
        using var affine = new Mat(2, 3, MatType.CV_64FC1);
        affine.Set(0, 0, 1.0);
        affine.Set(0, 1, 0.0);
        affine.Set(0, 2, 2.5); // translation.x lands exactly on a tie once inverted below
        affine.Set(1, 0, 0.0);
        affine.Set(1, 1, 1.0);
        affine.Set(1, 2, 1.5);

        // affine here maps crop -> temp directly as translation by (2.5, 1.5), so its own
        // inverse (used internally by CalculatePasteArea) is translation by (-2.5, -1.5); the
        // corner (0,0) maps to (-2.5, -1.5) and (1,1) maps to (-1.5, -0.5) — both exact ties.
        // Python cvRound / cv2.transform's int32 downcast rounds ties to even:
        // -2.5 -> -2, -1.5 -> -2, -0.5 -> 0. Confirmed against a standalone
        // `cv2.transform` call in Python during ground-truth generation for this module.
        var (pasteBoundingBox, pasteMatrix) = FaceHelper.CalculatePasteArea(temp, crop, affine);
        using var _pasteMatrix = pasteMatrix;

        Assert.Equal(0, pasteBoundingBox[0]); // clamped from -2 to 0
        Assert.Equal(0, pasteBoundingBox[1]); // clamped from -2 to 0
        Assert.Equal(0, pasteBoundingBox[2]); // max x is -2 or 0 depending on corner -> clamped to 0
        Assert.Equal(0, pasteBoundingBox[3]);
    }

    // -----------------------------------------------------------------
    // paste_back — real cv2 ground truth
    // -----------------------------------------------------------------

    private static Mat CreateDeterministicNoiseFrame(int height, int width, int seed)
    {
        var frame = new Mat(height, width, MatType.CV_8UC3);
        var random = new Random(seed);
        for (var r = 0; r < height; r++)
        {
            for (var c = 0; c < width; c++)
            {
                frame.Set(r, c, new Vec3b((byte)random.Next(256), (byte)random.Next(256), (byte)random.Next(256)));
            }
        }

        return frame;
    }

    /// <summary>Deterministic formulaic 150x150 BGR frame, computable identically in Python and
    /// C# (avoids embedding a large literal byte blob for a numpy RandomState stream, which
    /// uses a different PRNG algorithm than anything available in .NET and so could never be
    /// reproduced from a seed alone): B = (col*3) % 256, G = (row*5) % 256, R = (row+col) % 256.
    /// </summary>
    private static Mat CreateTempFrame150X150()
    {
        var frame = new Mat(150, 150, MatType.CV_8UC3);
        for (var r = 0; r < 150; r++)
        {
            for (var c = 0; c < 150; c++)
            {
                frame.Set(r, c, new Vec3b((byte)((c * 3) % 256), (byte)((r * 5) % 256), (byte)((r + c) % 256)));
            }
        }

        return frame;
    }

    /// <summary>Deterministic formulaic 80x80 BGR frame: B = (col*7+11) % 256,
    /// G = (row*3+17) % 256, R = (row*col+5) % 256. See <see cref="CreateTempFrame150X150"/>.</summary>
    private static Mat CreateCropFrame80X80()
    {
        var frame = new Mat(80, 80, MatType.CV_8UC3);
        for (var r = 0; r < 80; r++)
        {
            for (var c = 0; c < 80; c++)
            {
                frame.Set(r, c, new Vec3b((byte)(((c * 7) + 11) % 256), (byte)(((r * 3) + 17) % 256), (byte)(((r * c) + 5) % 256)));
            }
        }

        return frame;
    }

    [Fact]
    public void PasteBack_FullWhiteMask_MatchesPythonCv2()
    {
        using var temp = CreateTempFrame150X150();
        using var crop = CreateCropFrame80X80();
        using var mask = new Mat(80, 80, MatType.CV_32FC1, Scalar.All(1.0));

        var landmark5 = new float[,]
        {
            { 30f, 35f }, { 55f, 35f }, { 42f, 50f }, { 33f, 62f }, { 52f, 62f },
        };
        using var affine = FaceHelper.EstimateMatrixByFaceLandmark5(landmark5, WarpTemplate.Arcface112V1, new Size(80, 80));

        using var result = FaceHelper.PasteBack(temp, crop, mask, affine);

        Assert.Equal(new[] { 150, 150 }, new[] { result.Rows, result.Cols });
        AssertPixelSumClose(8946275L, SumPixels(result));
        AssertPixel(result, 10, 10, 75, 54, 118);
        AssertPixel(result, 100, 100, 44, 244, 200);
    }

    [Fact]
    public void PasteBack_PartialMask_BlendsAndMatchesPythonCv2()
    {
        using var temp = CreateTempFrame150X150();
        using var crop = CreateCropFrame80X80();
        using var mask = new Mat(80, 80, MatType.CV_32FC1);
        for (var r = 0; r < 80; r++)
        {
            for (var c = 0; c < 80; c++)
            {
                mask.Set(r, c, c < 40 ? 1.0f : 0.3f);
            }
        }

        var landmark5 = new float[,]
        {
            { 30f, 35f }, { 55f, 35f }, { 42f, 50f }, { 33f, 62f }, { 52f, 62f },
        };
        using var affine = FaceHelper.EstimateMatrixByFaceLandmark5(landmark5, WarpTemplate.Arcface112V1, new Size(80, 80));

        using var result = FaceHelper.PasteBack(temp, crop, mask, affine);

        AssertPixelSumClose(8966546L, SumPixels(result));
        AssertPixel(result, 20, 20, 142, 82, 157);
        // (20, 80) sits on the interpolation-sensitive mask-blend boundary (col 80 == crop
        // width); allow +/-1 for the same cross-OpenCV-build sub-pixel rounding difference
        // documented on AssertPixelSumClose.
        AssertPixel(result, 20, 80, 177, 94, 107, tolerance: 1);
        AssertPixel(result, 5, 5, 42, 40, 38);
    }

    [Fact]
    public void PasteBack_ZeroMask_LeavesTempFrameUnchanged()
    {
        using var temp = CreateDeterministicNoiseFrame(120, 120, 3);
        using var crop = CreateDeterministicNoiseFrame(64, 64, 9);
        using var mask = new Mat(64, 64, MatType.CV_32FC1, Scalar.All(0.0));
        var landmark5 = new float[,]
        {
            { 20f, 22f }, { 44f, 22f }, { 32f, 34f }, { 24f, 46f }, { 40f, 46f },
        };
        using var affine = FaceHelper.EstimateMatrixByFaceLandmark5(landmark5, WarpTemplate.Arcface112V1, new Size(64, 64));

        using var result = FaceHelper.PasteBack(temp, crop, mask, affine);

        for (var r = 0; r < 120; r++)
        {
            for (var c = 0; c < 120; c++)
            {
                Assert.Equal(temp.At<Vec3b>(r, c), result.At<Vec3b>(r, c));
            }
        }
    }

    [Fact]
    public void PasteBack_RequiresByteFrameAndFloatMask()
    {
        using var temp = new Mat(50, 50, MatType.CV_8UC3, Scalar.Black);
        using var crop = new Mat(20, 20, MatType.CV_8UC3, Scalar.Black);
        using var wrongMask = new Mat(20, 20, MatType.CV_8UC1, Scalar.All(255));
        var landmark5 = new float[,]
        {
            { 4f, 4f }, { 15f, 4f }, { 10f, 10f }, { 5f, 16f }, { 14f, 16f },
        };
        using var affine = FaceHelper.EstimateMatrixByFaceLandmark5(landmark5, WarpTemplate.Arcface112V1, new Size(20, 20));

        Assert.Throws<ArgumentException>(() => FaceHelper.PasteBack(temp, crop, wrongMask, affine));
    }

    // -----------------------------------------------------------------
    // create_rotation_matrix_and_size — real cv2 ground truth
    // -----------------------------------------------------------------

    [Theory]
    [InlineData(30, 100, 200, 186, 223)]
    [InlineData(0, 50, 50, 50, 50)]
    [InlineData(90, 64, 128, 128, 64)]
    [InlineData(45, 37, 53, 63, 63)]
    [InlineData(-30, 120, 80, 143, 129)]
    public void CreateRotationMatrixAndSize_MatchesPythonCv2(int angle, int width, int height, int expectedWidth, int expectedHeight)
    {
        var (matrix, size) = FaceHelper.CreateRotationMatrixAndSize(angle, new Size(width, height));
        using var _matrix = matrix;

        Assert.Equal(expectedWidth, size.Width);
        Assert.Equal(expectedHeight, size.Height);
    }

    [Fact]
    public void CreateRotationMatrixAndSize_30Degrees_MatchesPythonCv2MatrixValues()
    {
        var (matrix, _) = FaceHelper.CreateRotationMatrixAndSize(30, new Size(100, 200));
        using var _matrix = matrix;

        Assert.Equal(0.8660254037844387, matrix.At<double>(0, 0), MatrixTolerance);
        Assert.Equal(0.49999999999999994, matrix.At<double>(0, 1), MatrixTolerance);
        Assert.Equal(0.0, matrix.At<double>(0, 2), 3);
        Assert.Equal(-0.49999999999999994, matrix.At<double>(1, 0), MatrixTolerance);
        Assert.Equal(0.8660254037844387, matrix.At<double>(1, 1), MatrixTolerance);
        Assert.Equal(50.0, matrix.At<double>(1, 2), MatrixTolerance);
    }

    // -----------------------------------------------------------------
    // merge_matrix — pure double-precision math, verified against numpy.dot chain
    // -----------------------------------------------------------------

    [Fact]
    public void MergeMatrix_ThreeMatrices_MatchesNumpyDotChain()
    {
        using var a = MakeMatrix(1.0, 0.0, 5.0, 0.0, 1.0, 3.0);
        using var b = MakeMatrix(0.9, -0.1, 2.0, 0.1, 0.9, -4.0);
        using var c = MakeMatrix(1.1, 0.05, -1.0, -0.05, 1.1, 0.5);

        using var merged = FaceHelper.MergeMatrix(new[] { a, b, c });

        Assert.Equal(0.9950000000000001, merged.At<double>(0, 0), MatrixTolerance);
        Assert.Equal(-0.06500000000000002, merged.At<double>(0, 1), MatrixTolerance);
        Assert.Equal(5.780000000000001, merged.At<double>(0, 2), MatrixTolerance);
        Assert.Equal(0.06500000000000002, merged.At<double>(1, 0), MatrixTolerance);
        Assert.Equal(0.9950000000000001, merged.At<double>(1, 1), MatrixTolerance);
        Assert.Equal(-0.69, merged.At<double>(1, 2), MatrixTolerance);
    }

    private static Mat MakeMatrix(double m00, double m01, double m02, double m10, double m11, double m12)
    {
        var matrix = new Mat(2, 3, MatType.CV_64FC1);
        matrix.Set(0, 0, m00);
        matrix.Set(0, 1, m01);
        matrix.Set(0, 2, m02);
        matrix.Set(1, 0, m10);
        matrix.Set(1, 1, m11);
        matrix.Set(1, 2, m12);
        return matrix;
    }

    // -----------------------------------------------------------------
    // transform_points / transform_bounding_box — structural + numpy-derived checks
    // -----------------------------------------------------------------

    [Fact]
    public void TransformPoints_IdentityMatrix_ReturnsSamePoints()
    {
        using var identity = MakeMatrix(1, 0, 0, 0, 1, 0);
        var points = new float[,] { { 3f, 4f }, { -2f, 7.5f } };

        var result = FaceHelper.TransformPoints(points, identity);

        Assert.Equal((double)3f, (double)result[0, 0], precision: 4);
        Assert.Equal((double)4f, (double)result[0, 1], precision: 4);
        Assert.Equal((double)-2f, (double)result[1, 0], precision: 4);
        Assert.Equal((double)7.5f, (double)result[1, 1], precision: 4);
    }

    [Fact]
    public void TransformBoundingBox_TranslationMatrix_ShiftsBox()
    {
        using var translation = MakeMatrix(1, 0, 10, 0, 1, -5);
        var boundingBox = new float[] { 0, 0, 20, 30 };

        var result = FaceHelper.TransformBoundingBox(boundingBox, translation);

        Assert.Equal(new[] { 10f, -5f, 30f, 25f }, result);
    }

    // -----------------------------------------------------------------
    // Round-trip / invertibility property checks (secondary to the ground-truth checks above)
    // -----------------------------------------------------------------

    [Fact]
    public void EstimateMatrixByFaceLandmark5_ProducesInvertibleMatrix()
    {
        using var matrix = FaceHelper.EstimateMatrixByFaceLandmark5(SampleLandmark5, WarpTemplate.Arcface112V1, new Size(112, 112));
        using var inverse = new Mat();
        Cv2.InvertAffineTransform(matrix, inverse);

        // A 2x3 affine matrix followed by its inverse should compose to (approximately) the
        // identity on the linear part.
        var a00 = matrix.At<double>(0, 0);
        var a01 = matrix.At<double>(0, 1);
        var a10 = matrix.At<double>(1, 0);
        var a11 = matrix.At<double>(1, 1);
        var determinant = (a00 * a11) - (a01 * a10);

        Assert.True(Math.Abs(determinant) > 1e-6, "Estimated affine matrix must be non-degenerate.");
    }

    [Fact]
    public void WarpFaceByFaceLandmark5_ThenPasteBack_RoundTripsApproximately()
    {
        using var original = CreateGradientFrame();
        var (crop, matrix) = FaceHelper.WarpFaceByFaceLandmark5(original, SampleLandmark5, WarpTemplate.Arcface112V1, new Size(112, 112));
        using var _crop = crop;
        using var _matrix = matrix;
        using var mask = new Mat(112, 112, MatType.CV_32FC1, Scalar.All(1.0));

        using var pasted = FaceHelper.PasteBack(original, crop, mask, matrix);

        // With a full-strength mask, the region actually covered by the warp should match the
        // crop's own re-warp back into the frame closely (allowing for the two resampling
        // passes' interpolation error).
        Assert.Equal(original.Rows, pasted.Rows);
        Assert.Equal(original.Cols, pasted.Cols);
    }
}
