using FaceFusion.Processors;
using FaceFusion.Types;
using OpenCvSharp;

namespace FaceFusion.UnitTests;

/// <summary>
/// Port of the ground-truth checks for
/// <c>facefusion/processors/modules/face_swapper/{core,types,choices}.py</c> and
/// <c>facefusion/processors/pixel_boost.py</c>. There is no <c>tests/test_face_swapper.py</c>
/// or <c>tests/test_pixel_boost.py</c> in the Python suite (only
/// <c>tests/test_cli_face_swapper.py</c>, a CLI/subprocess smoke test that belongs to a later
/// CLI-layer port phase, not this one), so every case below was derived by hand from the
/// modules' numpy semantics and cross-checked against a live Python REPL — the exact values in
/// the pixel-boost round-trip case were generated by running Python's real
/// <c>implode_pixel_boost</c>/<c>explode_pixel_boost</c> on a synthetic 4x4 array (see that
/// test's comment for the transcript). Real end-to-end ONNX model coverage lives in
/// <c>tests/FaceFusion.ParityTests/FaceSwapperParityTests.cs</c>, ground truth captured by
/// <c>tools/parity/dump_face_swapper.py</c>.
/// </summary>
public sealed class FaceSwapperTests
{
    // -----------------------------------------------------------------
    // create_static_model_set / choices.py
    // -----------------------------------------------------------------

    [Fact]
    public void ModelCatalogHasThirteenModels()
    {
        var catalog = FaceSwapper.CreateStaticModelSet(DownloadScope.Full);
        Assert.Equal(13, catalog.Count);
        Assert.Equal(13, FaceSwapper.FaceSwapperModels.Count);

        foreach (var model in FaceSwapper.FaceSwapperModels)
        {
            Assert.True(catalog.ContainsKey(model), $"{model} missing from the catalog.");
        }
    }

    [Theory]
    [InlineData(FaceSwapperModel.BlendSwap256, FaceSwapperModelKind.BlendSwap, WarpTemplate.Ffhq512, 256, 0f, 1f)]
    [InlineData(FaceSwapperModel.Ghost1256, FaceSwapperModelKind.Ghost, WarpTemplate.Arcface112V1, 256, 0.5f, 0.5f)]
    [InlineData(FaceSwapperModel.HifiFaceUnofficial256, FaceSwapperModelKind.HifiFace, WarpTemplate.Mtcnn512, 256, 0.5f, 0.5f)]
    [InlineData(FaceSwapperModel.Hyperswap1a256, FaceSwapperModelKind.Hyperswap, WarpTemplate.Arcface128, 256, 0.5f, 0.5f)]
    [InlineData(FaceSwapperModel.Inswapper128, FaceSwapperModelKind.Inswapper, WarpTemplate.Arcface128, 128, 0f, 1f)]
    [InlineData(FaceSwapperModel.Simswap256, FaceSwapperModelKind.Simswap, WarpTemplate.Arcface112V1, 256, 0.485f, 0.229f)] // mean[0]/std[0] only
    [InlineData(FaceSwapperModel.SimswapUnofficial512, FaceSwapperModelKind.Simswap, WarpTemplate.Arcface112V1, 512, 0f, 1f)]
    [InlineData(FaceSwapperModel.Uniface256, FaceSwapperModelKind.Uniface, WarpTemplate.Ffhq512, 256, 0.5f, 0.5f)]
    public void ModelCatalogEntryMatchesPythonLiterals(FaceSwapperModel model, FaceSwapperModelKind expectedKind, WarpTemplate expectedTemplate, int expectedSize, float expectedMean0, float expectedStd0)
    {
        var options = FaceSwapper.CreateStaticModelSet(DownloadScope.Full)[model];

        Assert.Equal(expectedKind, options.Type);
        Assert.Equal(expectedTemplate, options.Template);
        Assert.Equal(expectedSize, options.Size.Width);
        Assert.Equal(expectedSize, options.Size.Height);
        Assert.Equal((double)expectedMean0, options.Mean[0], 6);
        Assert.Equal((double)expectedStd0, options.StandardDeviation[0], 6);
        Assert.True(options.Sources.ContainsKey("face_swapper"));
        Assert.True(options.Hashes.ContainsKey("face_swapper"));
    }

    [Theory]
    [InlineData(FaceSwapperModel.Ghost1256, "crossface_ghost")]
    [InlineData(FaceSwapperModel.HifiFaceUnofficial256, "crossface_hififace")]
    [InlineData(FaceSwapperModel.Simswap256, "crossface_simswap")]
    public void GhostHifiFaceSimswapHaveAnEmbeddingConverter(FaceSwapperModel model, string expectedFileNameStem)
    {
        var options = FaceSwapper.CreateStaticModelSet(DownloadScope.Full)[model];

        Assert.True(options.Sources.ContainsKey("embedding_converter"));
        Assert.Contains(expectedFileNameStem, options.Sources["embedding_converter"].Path);
    }

    [Theory]
    [InlineData(FaceSwapperModel.BlendSwap256)]
    [InlineData(FaceSwapperModel.Hyperswap1a256)]
    [InlineData(FaceSwapperModel.Inswapper128)]
    [InlineData(FaceSwapperModel.Uniface256)]
    public void ModelsWithoutAnEmbeddingConverterDoNotHaveOne(FaceSwapperModel model)
    {
        var options = FaceSwapper.CreateStaticModelSet(DownloadScope.Full)[model];
        Assert.False(options.Sources.ContainsKey("embedding_converter"));
    }

    [Fact]
    public void Hyperswap1aFp16PrecisionMatchesPython()
    {
        var options = FaceSwapper.CreateStaticModelSet(DownloadScope.Full)[FaceSwapperModel.Hyperswap1a256];
        Assert.Equal("fp16", options.Precision);
    }

    [Fact]
    public void PixelBoostChoicesMatchPythonForEveryModel()
    {
        Assert.Equal(13, FaceSwapper.FaceSwapperPixelBoostChoices.Count);
        Assert.Equal(new[] { "128x128", "256x256", "384x384", "512x512", "768x768", "1024x1024" }, FaceSwapper.FaceSwapperPixelBoostChoices[FaceSwapperModel.Inswapper128]);
        Assert.Equal(new[] { "512x512", "768x768", "1024x1024" }, FaceSwapper.FaceSwapperPixelBoostChoices[FaceSwapperModel.SimswapUnofficial512]);
        Assert.Equal(new[] { "256x256", "512x512", "768x768", "1024x1024" }, FaceSwapper.FaceSwapperPixelBoostChoices[FaceSwapperModel.Uniface256]);
    }

    [Fact]
    public void WeightRangeMatchesPythonCreateFloatRange()
    {
        // Python: create_float_range(0.0, 1.0, 0.05) -> 21 values, 0.0..1.0 inclusive.
        Assert.Equal(21, FaceSwapper.FaceSwapperWeightRange.Count);
        Assert.Equal(0.0, FaceSwapper.FaceSwapperWeightRange[0], 9);
        Assert.Equal(1.0, FaceSwapper.FaceSwapperWeightRange[^1], 9);
    }

    // -----------------------------------------------------------------
    // pixel_boost.py — implode/explode round trip, verified against a real Python transcript
    // -----------------------------------------------------------------

    /// <summary>
    /// Ground truth from a live Python session (numpy 2.4.6):
    /// <code>
    /// img = numpy.arange(4*4*3).reshape(4,4,3).astype(numpy.uint8)
    /// implode_pixel_boost(img, 2, (2,2))[:, :, :, 0]
    /// # sub-image 0 (channel 0): [[0, 6], [24, 30]]
    /// # sub-image 1 (channel 0): [[3, 9], [27, 33]]
    /// # sub-image 2 (channel 0): [[12, 18], [36, 42]]
    /// # sub-image 3 (channel 0): [[15, 21], [39, 45]]
    /// explode_pixel_boost(list(sub_images), 2, (2,2), (4,4)) == img  # True
    /// </code>
    /// Confirms <see cref="PixelBoost.ImplodePixelBoost"/> is a strided "pixel unshuffle", not a
    /// coarse block tiling — see the class remarks in <c>PixelBoost.cs</c>.
    /// </summary>
    [Fact]
    public void ImplodePixelBoostMatchesPythonStridedUnshuffle()
    {
        using var image = new Mat(4, 4, MatType.CV_8UC3);
        var value = 0;
        for (var row = 0; row < 4; row++)
        {
            for (var col = 0; col < 4; col++)
            {
                image.Set(row, col, new Vec3b((byte)value, (byte)(value + 1), (byte)(value + 2)));
                value += 3;
            }
        }

        var subImages = PixelBoost.ImplodePixelBoost(image, pixelBoostTotal: 2, modelSize: new Size(2, 2));

        try
        {
            Assert.Equal(4, subImages.Count);

            AssertChannel0(subImages[0], new byte[,] { { 0, 6 }, { 24, 30 } });
            AssertChannel0(subImages[1], new byte[,] { { 3, 9 }, { 27, 33 } });
            AssertChannel0(subImages[2], new byte[,] { { 12, 18 }, { 36, 42 } });
            AssertChannel0(subImages[3], new byte[,] { { 15, 21 }, { 39, 45 } });
        }
        finally
        {
            foreach (var subImage in subImages)
            {
                subImage.Dispose();
            }
        }
    }

    private static void AssertChannel0(Mat subImage, byte[,] expected)
    {
        for (var row = 0; row < 2; row++)
        {
            for (var col = 0; col < 2; col++)
            {
                Assert.Equal(expected[row, col], subImage.At<Vec3b>(row, col).Item0);
            }
        }
    }

    [Fact]
    public void ExplodePixelBoostIsTheExactInverseOfImplode()
    {
        using var image = new Mat(4, 4, MatType.CV_8UC3);
        var random = new Random(42);
        for (var row = 0; row < 4; row++)
        {
            for (var col = 0; col < 4; col++)
            {
                image.Set(row, col, new Vec3b((byte)random.Next(256), (byte)random.Next(256), (byte)random.Next(256)));
            }
        }

        var subImages = PixelBoost.ImplodePixelBoost(image, pixelBoostTotal: 2, modelSize: new Size(2, 2));
        using var reconstructed = PixelBoost.ExplodePixelBoost(subImages, pixelBoostTotal: 2, modelSize: new Size(2, 2), pixelBoostSize: new Size(4, 4));

        foreach (var subImage in subImages)
        {
            subImage.Dispose();
        }

        for (var row = 0; row < 4; row++)
        {
            for (var col = 0; col < 4; col++)
            {
                Assert.Equal(image.At<Vec3b>(row, col), reconstructed.At<Vec3b>(row, col));
            }
        }
    }

    [Fact]
    public void PixelBoostTotalOneIsTheIdentity()
    {
        using var image = new Mat(4, 4, MatType.CV_8UC3, new Scalar(10, 20, 30));

        var subImages = PixelBoost.ImplodePixelBoost(image, pixelBoostTotal: 1, modelSize: new Size(4, 4));
        try
        {
            Assert.Single(subImages);
            for (var row = 0; row < 4; row++)
            {
                for (var col = 0; col < 4; col++)
                {
                    Assert.Equal(image.At<Vec3b>(row, col), subImages[0].At<Vec3b>(row, col));
                }
            }
        }
        finally
        {
            foreach (var subImage in subImages)
            {
                subImage.Dispose();
            }
        }
    }

    // -----------------------------------------------------------------
    // prepare_crop_frame — the shared 'target' model input, every model kind
    // -----------------------------------------------------------------

    [Fact]
    public void PrepareCropFrameReversesChannelsAndNormalizes()
    {
        using var crop = new Mat(1, 1, MatType.CV_8UC3);
        crop.Set(0, 0, new Vec3b(10, 20, 30)); // B=10, G=20, R=30

        var mean = new[] { 0.5f, 0.5f, 0.5f };
        var std = new[] { 0.5f, 0.5f, 0.5f };

        var chw = FaceSwapper.PrepareCropFrame(crop, mean, std);

        Assert.Equal(3, chw.Length);
        AssertClose(((30 / 255.0) - 0.5) / 0.5, chw[0]); // R -> channel 0
        AssertClose(((20 / 255.0) - 0.5) / 0.5, chw[1]); // G -> channel 1
        AssertClose(((10 / 255.0) - 0.5) / 0.5, chw[2]); // B -> channel 2
    }

    [Fact]
    public void PrepareCropFrameWithZeroMeanUnitStdIsJustNormalizedChannelReversal()
    {
        using var crop = new Mat(1, 1, MatType.CV_8UC3);
        crop.Set(0, 0, new Vec3b(0, 128, 255));

        var mean = new[] { 0f, 0f, 0f };
        var std = new[] { 1f, 1f, 1f };

        var chw = FaceSwapper.PrepareCropFrame(crop, mean, std);

        AssertClose(255 / 255.0, chw[0]);
        AssertClose(128 / 255.0, chw[1]);
        AssertClose(0 / 255.0, chw[2]);
    }

    // -----------------------------------------------------------------
    // prepare_source_frame — blendswap / uniface
    // -----------------------------------------------------------------

    [Fact]
    public void PrepareSourceFrameForBlendSwapWarpsTo112x112()
    {
        using var source = new Mat(200, 200, MatType.CV_8UC3, new Scalar(50, 60, 70));
        var landmark5 = CenteredSquareLandmark5(200, 200);

        var chw = FaceSwapper.PrepareSourceFrame(FaceSwapperModelKind.BlendSwap, landmark5, source);

        // (1, 3, 112, 112) flattened.
        Assert.Equal(3 * 112 * 112, chw.Length);
    }

    [Fact]
    public void PrepareSourceFrameForUnifaceWarpsTo256x256()
    {
        using var source = new Mat(200, 200, MatType.CV_8UC3, new Scalar(50, 60, 70));
        var landmark5 = CenteredSquareLandmark5(200, 200);

        var chw = FaceSwapper.PrepareSourceFrame(FaceSwapperModelKind.Uniface, landmark5, source);

        Assert.Equal(3 * 256 * 256, chw.Length);
    }

    private static float[,] CenteredSquareLandmark5(int width, int height)
    {
        // Rough eye/nose/mouth-corner layout, scaled to the frame — real detector output shape,
        // synthetic values (this test only asserts output shape/dtype, not warp geometry, which
        // is FaceHelper.WarpFaceByFaceLandmark5's own, already parity-tested responsibility).
        return new float[,]
        {
            { width * 0.35f, height * 0.4f },
            { width * 0.65f, height * 0.4f },
            { width * 0.5f, height * 0.55f },
            { width * 0.4f, height * 0.7f },
            { width * 0.6f, height * 0.7f },
        };
    }

    // -----------------------------------------------------------------
    // balance_source_embedding
    // -----------------------------------------------------------------

    [Fact]
    public void BalanceSourceEmbeddingAtWeightZeroFiveIsPureSourceNotTheMidpoint()
    {
        // Python: interp(0.5, [0,1], [0.35,-0.35]) == 0.0 exactly (the midpoint of the
        // *effective* weight range, not of the [0,1] UI slider) -> the target's contribution
        // is multiplied by 0, so face_swapper_weight = 0.5 is pure source identity, not a
        // source/target midpoint blend. Counterintuitive; reproduced exactly, not "fixed".
        var source = new[] { 1f, 2f, 3f };
        var target = new[] { 3f, 2f, 1f };

        var result = FaceSwapper.BalanceSourceEmbedding(FaceSwapperModelKind.Ghost, source, target, faceSwapperWeight: 0.5);

        AssertClose(1.0, result[0]);
        AssertClose(2.0, result[1]);
        AssertClose(3.0, result[2]);
    }

    [Fact]
    public void BalanceSourceEmbeddingAtWeightZeroIsPureSource()
    {
        // Python: interp(0, [0,1], [0.35,-0.35]) == 0.35 (not 0!) — weight=0 does NOT mean
        // "100% source", it means a 0.35 blend toward source. Reproduced exactly, not "fixed".
        var source = new[] { 1f, 0f };
        var target = new[] { 0f, 1f };

        var result = FaceSwapper.BalanceSourceEmbedding(FaceSwapperModelKind.Ghost, source, target, faceSwapperWeight: 0.0);

        // result = source*(1-0.35) + target*0.35 = source*0.65 + target*0.35
        AssertClose((1.0 * 0.65) + (0.0 * 0.35), result[0]);
        AssertClose((0.0 * 0.65) + (1.0 * 0.35), result[1]);
    }

    [Fact]
    public void BalanceSourceEmbeddingRenormalizesTargetForInswapperButNotForGhost()
    {
        var source = new[] { 0f, 0f };
        var target = new[] { 3f, 4f }; // norm = 5

        var ghostResult = FaceSwapper.BalanceSourceEmbedding(FaceSwapperModelKind.Ghost, source, target, faceSwapperWeight: 1.0);
        var inswapperResult = FaceSwapper.BalanceSourceEmbedding(FaceSwapperModelKind.Inswapper, source, target, faceSwapperWeight: 1.0);

        // weight=1 -> interp = -0.35, i.e. result = source*1.35 + target*(-0.35) = -0.35*target
        // (source is all-zero here, so result is entirely the (possibly renormalized) target term).
        AssertClose(-0.35 * 3.0, ghostResult[0]); // raw target, not renormalized
        AssertClose(-0.35 * 4.0, ghostResult[1]);

        AssertClose(-0.35 * (3.0 / 5.0), inswapperResult[0]); // target / ||target||
        AssertClose(-0.35 * (4.0 / 5.0), inswapperResult[1]);
    }

    // -----------------------------------------------------------------
    // normalize_crop_frame — dtype and math both verified
    // -----------------------------------------------------------------

    [Fact]
    public void NormalizeCropFrameForInswapperStaysFloat32AndSkipsRenormalize()
    {
        // 1x1 CHW: R=0.6, G=0.4, B=0.2 (already in [0,1], as a real model output would be).
        var chw = new[] { 0.6f, 0.4f, 0.2f };
        var mean = new[] { 0f, 0f, 0f };
        var std = new[] { 1f, 1f, 1f };

        using var result = FaceSwapper.NormalizeCropFrame(chw, height: 1, width: 1, FaceSwapperModelKind.Inswapper, mean, std);

        Assert.Equal(MatType.CV_32FC3, result.Type());
        var pixel = result.At<Vec3f>(0, 0);
        AssertClose(0.2 * 255, pixel.Item0); // B
        AssertClose(0.4 * 255, pixel.Item1); // G
        AssertClose(0.6 * 255, pixel.Item2); // R
    }

    [Fact]
    public void NormalizeCropFrameForGhostPromotesToFloat64AndRenormalizes()
    {
        var chw = new[] { 0.2f, 0.2f, 0.2f }; // R, G, B channel planes (1x1 each)
        var mean = new[] { 0.5f, 0.5f, 0.5f };
        var std = new[] { 0.5f, 0.5f, 0.5f };

        using var result = FaceSwapper.NormalizeCropFrame(chw, height: 1, width: 1, FaceSwapperModelKind.Ghost, mean, std);

        Assert.Equal(MatType.CV_64FC3, result.Type());
        // value = 0.2 * 0.5 + 0.5 = 0.6, clip(0,1) is a no-op, * 255 = 153
        var pixel = result.At<Vec3d>(0, 0);
        AssertClose(0.6 * 255, pixel.Item0);
        AssertClose(0.6 * 255, pixel.Item1);
        AssertClose(0.6 * 255, pixel.Item2);
    }

    [Fact]
    public void NormalizeCropFrameClipsBeforeRenormalizeRangeExceeded()
    {
        // A model output that, after renormalize, would exceed [0,1] must clip to it before
        // the *255, matching Python's `.clip(0, 1)` — not clip the final *255 result.
        var chw = new[] { 2.0f, -2.0f, 0.5f };
        var mean = new[] { 0.5f, 0.5f, 0.5f };
        var std = new[] { 0.5f, 0.5f, 0.5f };

        using var result = FaceSwapper.NormalizeCropFrame(chw, height: 1, width: 1, FaceSwapperModelKind.Uniface, mean, std);

        var pixel = result.At<Vec3d>(0, 0);
        // R: 2.0*0.5+0.5 = 1.5 -> clip -> 1.0 -> *255 = 255 (channel R lands at Item2, BGR)
        AssertClose(255.0, pixel.Item2);
        // G: -2.0*0.5+0.5 = -0.5 -> clip -> 0.0 -> *255 = 0
        AssertClose(0.0, pixel.Item1);
    }

    // -----------------------------------------------------------------
    // helpers
    // -----------------------------------------------------------------

    private static void AssertClose(double expected, double actual, double tolerance = 1e-6)
    {
        Assert.True(Math.Abs(expected - actual) <= tolerance, $"expected {expected}, got {actual}");
    }
}
