using System.Text.Json;
using FaceFusion.Inference;

namespace FaceFusion.UnitTests;

/// <summary>
/// Tests for <see cref="ModelHelper"/> / <see cref="OnnxProtoReader"/> — the port of
/// facefusion/model_helper.py's <c>get_static_model_initializer</c>.
///
/// <para>
/// Most cases replay <c>.onnx</c> files generated by
/// <c>tools/parity/generate_onnx_fixtures.py</c> using the real <c>onnx</c> Python
/// package (onnx.helper.make_tensor / onnx.numpy_helper), with expected values taken
/// straight from <c>onnx.numpy_helper.to_array(onnx.load(path).graph.initializer[-1])</c>
/// — the exact call model_helper.py wraps — so these check parity with the real
/// implementation, not just with this port's own reading of the spec.
/// </para>
///
/// <para>
/// A handful of edge cases the <c>onnx</c> package will not produce on purpose (unpacked
/// repeated scalar fields, <c>external_data</c>, a <c>TensorProto.segment</c> split, a
/// truncated file, a graph with no initializers) are hand-built directly as protobuf
/// bytes below using a tiny writer, since they exercise error handling this reader must
/// have but a well-formed exporter never triggers.
/// </para>
/// </summary>
public sealed class ModelHelperTests
{
    private static string FixturesDirectory
    {
        get
        {
            var directory = new DirectoryInfo(AppContext.BaseDirectory);

            while (directory != null)
            {
                if (File.Exists(Path.Combine(directory.FullName, "FaceFusion.sln")))
                {
                    return Path.Combine(directory.FullName, "tests", "FaceFusion.UnitTests", "fixtures", "onnx");
                }

                directory = directory.Parent;
            }

            throw new InvalidOperationException("Could not locate FaceFusion.sln above " + AppContext.BaseDirectory);
        }
    }

    private static JsonElement Manifest
    {
        get
        {
            var manifestPath = Path.Combine(FixturesDirectory, "manifest.json");
            return JsonDocument.Parse(File.ReadAllText(manifestPath)).RootElement;
        }
    }

    public static IEnumerable<object[]> FixtureCases()
    {
        foreach (var entry in Manifest.EnumerateObject())
        {
            yield return new object[] { entry.Name };
        }
    }

    // -----------------------------------------------------------------
    // Fixtures generated by the real `onnx` package — parity with onnx.numpy_helper.
    // -----------------------------------------------------------------

    [Theory]
    [MemberData(nameof(FixtureCases))]
    public void MatchesOnnxNumpyHelperReference(string caseName)
    {
        var manifestEntry = Manifest.GetProperty(caseName);
        var expectedShape = manifestEntry.GetProperty("shape").EnumerateArray().Select(e => e.GetInt64()).ToArray();
        var expectedDType = manifestEntry.GetProperty("dtype").GetString();
        var expectedValues = manifestEntry.GetProperty("values").EnumerateArray().Select(e => e.GetDouble()).ToArray();

        var modelPath = Path.Combine(FixturesDirectory, caseName + ".onnx");
        var tensor = ModelHelper.GetStaticModelInitializer(modelPath);

        Assert.Equal(expectedShape, tensor.Shape);
        Assert.Equal(expectedDType, tensor.DType);

        var actualValues = tensor.AsDoubles();
        Assert.Equal(expectedValues.Length, actualValues.Length);

        for (var i = 0; i < expectedValues.Length; i++)
        {
            // float16 has ~3 decimal digits of precision; float32/int/double fixtures
            // round-trip exactly, so a tight-but-nonzero tolerance covers every case
            // uniformly without special-casing dtypes here.
            Assert.Equal(expectedValues[i], actualValues[i], precision: 3);
        }
    }

    [Fact]
    public void PicksTheLastInitializerNotTheFirstOrBiggest()
    {
        // multi_last_is_int64_raw.onnx has 3 initializers: float32 'first', int32
        // 'middle', int64 'last'. A bug that returned the first or the type-widest
        // initializer would fail this in a way the parametrised parity test alone might
        // not make obvious.
        var modelPath = Path.Combine(FixturesDirectory, "multi_last_is_int64_raw.onnx");
        var tensor = ModelHelper.GetStaticModelInitializer(modelPath);

        Assert.Equal("int64", tensor.DType);
        Assert.Equal(new long[] { 2, 2 }, tensor.Shape);
        Assert.Equal(new long[] { 9, -9, 8, -8 }, tensor.AsDoubles().Select(v => (long)v).ToArray());
    }

    [Fact]
    public void CachesRepeatedCallsForTheSamePath()
    {
        // Python: @lru_cache() — a second call with the same model_path must not re-parse
        // the file. This port's cache (see ModelHelper) is a ConcurrentDictionary, not
        // Python's lru_cache, so "cached" is verified by content equality plus the file
        // still being readable, rather than by object identity (the factory always
        // builds a fresh OnnxTensor; GetOrAdd is what avoids the second parse).
        var modelPath = Path.Combine(FixturesDirectory, "single_float32_raw.onnx");

        var first = ModelHelper.GetStaticModelInitializer(modelPath);
        var second = ModelHelper.GetStaticModelInitializer(modelPath);

        Assert.Same(first, second);
    }

    // -----------------------------------------------------------------
    // Hand-built protobuf edge cases — things a well-formed onnx export never produces,
    // but which a minimal wire-format reader must still handle correctly or reject
    // clearly rather than silently returning garbage.
    // -----------------------------------------------------------------

    [Fact]
    public void AcceptsUnpackedRepeatedScalarFields()
    {
        // proto3 defaults repeated scalar fields to packed encoding (what every
        // onnx-generated fixture above uses), but the wire format still permits the
        // legacy unpacked form: one tag+value per element instead of one packed blob.
        // Build an int64_data field that way by hand.
        var tensor = new TensorBuilder()
            .Dims(3)
            .DataType(7) // INT64
            .UnpackedInt64Data(7, new long[] { 10, -20, 30 })
            .Build();

        var modelPath = WriteTempModel(new GraphBuilder().Initializer(tensor).Build());
        var result = ModelHelper.GetStaticModelInitializer(modelPath);

        Assert.Equal("int64", result.DType);
        Assert.Equal(new long[] { 3 }, result.Shape);
        Assert.Equal(new long[] { 10, -20, 30 }, result.AsDoubles().Select(v => (long)v).ToArray());
    }

    [Fact]
    public void RejectsExternalDataViaDataLocation()
    {
        var tensor = new TensorBuilder()
            .Dims(2)
            .DataType(1) // FLOAT
            .Name("weights")
            .VarintField(14, 1) // data_location = EXTERNAL
            .Build();

        var modelPath = WriteTempModel(new GraphBuilder().Initializer(tensor).Build());

        var exception = Assert.Throws<NotSupportedException>(() => ModelHelper.GetStaticModelInitializer(modelPath));
        Assert.Contains("externally", exception.Message, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("weights", exception.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void RejectsExternalDataEntries()
    {
        // Even without an explicit data_location, a populated external_data field (13)
        // means the bytes live in a side file this reader never opens.
        var externalDataEntry = new byte[]
        {
            0x0A, 0x08, // field 1 (key), length 8
            (byte)'l', (byte)'o', (byte)'c', (byte)'a', (byte)'t', (byte)'i', (byte)'o', (byte)'n',
        };

        var tensor = new TensorBuilder()
            .Dims(2)
            .DataType(1)
            .LengthDelimitedField(13, externalDataEntry)
            .Build();

        var modelPath = WriteTempModel(new GraphBuilder().Initializer(tensor).Build());

        var exception = Assert.Throws<NotSupportedException>(() => ModelHelper.GetStaticModelInitializer(modelPath));
        Assert.Contains("externally", exception.Message, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void RejectsSegmentedTensors()
    {
        var tensor = new TensorBuilder()
            .Dims(2)
            .DataType(1)
            .LengthDelimitedField(3, Array.Empty<byte>()) // segment
            .RawData(new byte[8]) // otherwise-valid payload, so segment is what trips it
            .Build();

        var modelPath = WriteTempModel(new GraphBuilder().Initializer(tensor).Build());

        var exception = Assert.Throws<NotSupportedException>(() => ModelHelper.GetStaticModelInitializer(modelPath));
        Assert.Contains("segment", exception.Message, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void RejectsUnsupportedDataTypes()
    {
        // STRING = 8, deliberately not in ModelHelper's supported set.
        var tensor = new TensorBuilder()
            .Dims(1)
            .DataType(8)
            .Build();

        var modelPath = WriteTempModel(new GraphBuilder().Initializer(tensor).Build());

        var exception = Assert.Throws<NotSupportedException>(() => ModelHelper.GetStaticModelInitializer(modelPath));
        Assert.Contains("data_type 8", exception.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void ThrowsWhenModelHasNoGraph()
    {
        var modelPath = Path.Combine(Path.GetTempPath(), "model-helper-tests-" + Guid.NewGuid().ToString("N") + ".onnx");
        File.WriteAllBytes(modelPath, Array.Empty<byte>());

        try
        {
            Assert.Throws<InvalidDataException>(() => ModelHelper.GetStaticModelInitializer(modelPath));
        }
        finally
        {
            File.Delete(modelPath);
        }
    }

    [Fact]
    public void ThrowsWhenGraphHasNoInitializers()
    {
        var modelPath = WriteTempModel(new GraphBuilder().Build());

        Assert.Throws<InvalidDataException>(() => ModelHelper.GetStaticModelInitializer(modelPath));
    }

    [Fact]
    public void ThrowsOnTruncatedFile()
    {
        // Cut the file in half rather than trimming just a few trailing bytes: onnx
        // serializes ModelProto fields in ascending field-number order, so
        // opset_import (field 8) is written *after* graph (field 7) — trimming only a
        // handful of trailing bytes would corrupt that unrelated trailer instead of the
        // tensor data this reader actually needs, and would not exercise the failure
        // path at all. Halving the file guarantees the cut lands inside the graph.
        var sourcePath = Path.Combine(FixturesDirectory, "single_float32_raw.onnx");
        var fullBytes = File.ReadAllBytes(sourcePath);
        var truncatedBytes = fullBytes[..(fullBytes.Length / 2)];

        var modelPath = Path.Combine(Path.GetTempPath(), "model-helper-tests-" + Guid.NewGuid().ToString("N") + ".onnx");
        File.WriteAllBytes(modelPath, truncatedBytes);

        try
        {
            // Truncation can be detected at different points (a length-prefixed field
            // whose declared length runs past EOF, a raw_data byte count that no longer
            // matches dims, or a bare EOF mid-varint), so this only pins "fails loudly",
            // not a single exception subtype.
            Assert.ThrowsAny<Exception>(() => ModelHelper.GetStaticModelInitializer(modelPath));
        }
        finally
        {
            File.Delete(modelPath);
        }
    }

    [Fact]
    public void RawDataTakesPrecedenceOverTypedFieldsWhenBothArePresent()
    {
        // Not a real-world onnx export (they never populate both), but the reader's
        // documented precedence (raw_data wins) should still be verified directly.
        var tensor = new TensorBuilder()
            .Dims(2)
            .DataType(6) // INT32
            .PackedInt32Data(5, new[] { 111, 222 }) // would decode to [111, 222] if used
            .RawData(BitConverter.GetBytes(1) .Concat(BitConverter.GetBytes(2)).ToArray()) // [1, 2]
            .Build();

        var modelPath = WriteTempModel(new GraphBuilder().Initializer(tensor).Build());
        var result = ModelHelper.GetStaticModelInitializer(modelPath);

        Assert.Equal(new long[] { 1, 2 }, result.AsDoubles().Select(v => (long)v).ToArray());
    }

    // -----------------------------------------------------------------
    // Minimal protobuf byte builders, used only by the hand-built edge cases above.
    // -----------------------------------------------------------------

    private static string WriteTempModel(byte[] graphBytes)
    {
        var buffer = new List<byte>();
        WriteLengthDelimitedField(buffer, 7, graphBytes); // ModelProto.graph = 7

        var modelPath = Path.Combine(Path.GetTempPath(), "model-helper-tests-" + Guid.NewGuid().ToString("N") + ".onnx");
        File.WriteAllBytes(modelPath, buffer.ToArray());
        return modelPath;
    }

    private static void WriteVarint(List<byte> buffer, ulong value)
    {
        while (value >= 0x80)
        {
            buffer.Add((byte)((value & 0x7F) | 0x80));
            value >>= 7;
        }

        buffer.Add((byte)value);
    }

    private static void WriteTag(List<byte> buffer, int fieldNumber, int wireType)
    {
        WriteVarint(buffer, (ulong)((fieldNumber << 3) | wireType));
    }

    private static void WriteVarintField(List<byte> buffer, int fieldNumber, ulong value)
    {
        WriteTag(buffer, fieldNumber, 0);
        WriteVarint(buffer, value);
    }

    private static void WriteLengthDelimitedField(List<byte> buffer, int fieldNumber, byte[] payload)
    {
        WriteTag(buffer, fieldNumber, 2);
        WriteVarint(buffer, (ulong)payload.Length);
        buffer.AddRange(payload);
    }

    private sealed class GraphBuilder
    {
        private readonly List<byte> initializers = new();

        public GraphBuilder Initializer(byte[] tensorBytes)
        {
            WriteLengthDelimitedField(initializers, 5, tensorBytes); // GraphProto.initializer = 5
            return this;
        }

        public byte[] Build() => initializers.ToArray();
    }

    private sealed class TensorBuilder
    {
        private readonly List<byte> buffer = new();

        public TensorBuilder Dims(params long[] dims)
        {
            var payload = new List<byte>();
            foreach (var dimension in dims)
            {
                WriteVarint(payload, unchecked((ulong)dimension));
            }

            WriteLengthDelimitedField(buffer, 1, payload.ToArray()); // TensorProto.dims = 1 (packed)
            return this;
        }

        public TensorBuilder DataType(int dataType)
        {
            WriteVarintField(buffer, 2, unchecked((ulong)dataType)); // TensorProto.data_type = 2
            return this;
        }

        public TensorBuilder Name(string name)
        {
            WriteLengthDelimitedField(buffer, 8, System.Text.Encoding.UTF8.GetBytes(name)); // TensorProto.name = 8
            return this;
        }

        public TensorBuilder RawData(byte[] bytes)
        {
            WriteLengthDelimitedField(buffer, 9, bytes); // TensorProto.raw_data = 9
            return this;
        }

        public TensorBuilder UnpackedInt64Data(int fieldNumber, long[] values)
        {
            foreach (var value in values)
            {
                WriteVarintField(buffer, fieldNumber, unchecked((ulong)value)); // one tag+varint per element
            }

            return this;
        }

        public TensorBuilder PackedInt32Data(int fieldNumber, int[] values)
        {
            var payload = new List<byte>();
            foreach (var value in values)
            {
                WriteVarint(payload, unchecked((ulong)(long)value));
            }

            WriteLengthDelimitedField(buffer, fieldNumber, payload.ToArray());
            return this;
        }

        public TensorBuilder VarintField(int fieldNumber, ulong value)
        {
            WriteVarintField(buffer, fieldNumber, value);
            return this;
        }

        public TensorBuilder LengthDelimitedField(int fieldNumber, byte[] payload)
        {
            WriteLengthDelimitedField(buffer, fieldNumber, payload);
            return this;
        }

        public byte[] Build() => buffer.ToArray();
    }
}
