"""
Generate src/FaceFusion.Cli/CliOptions.cs from facefusion/program.py.

Every CLI flag appears in job JSON and in user scripts, so a renamed or retyped option is
a breaking change. Generating the C# table from the Python source means the two cannot
drift; CliOptionsTests asserts the generated table still matches program.py.

Usage: python3 tools/parity/generate_cli_options.py
"""

import re

PROGRAM_PATH = 'facefusion/program.py'
# Processor options are registered by each processor's register_args(), NOT by program.py.
# Scanning program.py alone misses 22 flags; comparing against the real `--help` output is
# what exposed that.
PROCESSOR_GLOB = 'facefusion/processors/modules/*/core.py'
OUTPUT_PATH = 'src/FaceFusion.Cli/CliOptions.cs'


def parse_options():
	import glob

	source = open(PROGRAM_PATH).read()

	for path in sorted(glob.glob(PROCESSOR_GLOB)):
		source += open(path).read()

	rows, seen = [], set()

	# Options may declare a short alias first, e.g. add_argument('-s', '--source-paths').
	# Matching only on a leading long flag silently drops those - it dropped
	# --source-paths, --target-path and --output-path, the three most important flags
	# in the whole surface.
	for match in re.finditer(r"add_argument\(\s*(?:'(-[a-zA-Z])'\s*,\s*)?'(--[a-z0-9-]+)'(.*?)\)\n", source, re.S):
		alias, flag, rest = match.group(1), match.group(2), match.group(3)

		if flag in seen:
			continue
		seen.add(flag)

		argument_type = (re.search(r"type\s*=\s*([\w.]+)", rest) or [ None, 'str' ])[1]
		action = (re.search(r"action\s*=\s*'([\w_]+)'", rest) or [ None, None ])[1]
		nargs = (re.search(r"nargs\s*=\s*'([^']+)'", rest) or [ None, None ])[1]

		if action == 'store_true':
			kind = 'Flag'
		elif nargs == '+':
			# functools.partial(...) wraps a numeric caster in every case it is used.
			kind = 'IntList' if argument_type in ('int', 'partial') else 'StringList'
		elif argument_type == 'int':
			kind = 'Int'
		elif argument_type == 'float':
			kind = 'Float'
		else:
			kind = 'String'

		rows.append((flag, flag[2:].replace('-', '_'), kind, alias or ''))

	return rows


COMMANDS = [
	'job-list', 'job-create', 'job-submit', 'job-submit-all', 'job-delete', 'job-delete-all',
	'job-add-step', 'job-remix-step', 'job-insert-step', 'job-remove-step',
	'job-run', 'job-run-all', 'job-retry', 'job-retry-all',
	'headless-run', 'batch-run', 'force-download', 'benchmark', 'run'
]


def capture_command_flags():
	"""
	Ask the real Python CLI which flags each subcommand accepts.

	Deriving this from the argparse source is fragile - an earlier version of this script
	parsed program.py with a regex that missed any option declaring a short alias first
	(dropping --source-paths, --target-path and --output-path), and the drift test used the
	same regex, so it confirmed the bug instead of catching it. Shelling out to --help is
	authoritative because it is the same surface a user sees.
	"""
	import subprocess

	flags_by_command = {}

	for command in COMMANDS:
		try:
			result = subprocess.run([ 'python3', 'facefusion.py', command, '--help' ],
				capture_output = True, text = True, timeout = 300)
		except Exception:
			continue

		flags = sorted(set(re.findall(r'--[a-z0-9-]+', result.stdout)) - { '--help' })

		if flags:
			flags_by_command[command] = flags

	return flags_by_command


def main():
	rows = parse_options()
	entries = ',\n'.join('        new("%s", "%s", CliValueKind.%s, %s)'
		% (row[0], row[1], row[2], '"%s"' % row[3] if row[3] else 'null') for row in rows)
	header = open(OUTPUT_PATH).read().split('public static class CliOptions')[0]
	open(OUTPUT_PATH, 'w').write(
		header
		+ 'public static class CliOptions\n{\n'
		+ '    public static readonly IReadOnlyList<CliOption> All = new CliOption[]\n    {\n'
		+ entries + '\n    };\n}\n')

	flags_by_command = capture_command_flags()

	if flags_by_command:
		lines = [
			'namespace FaceFusion.Cli;',
			'',
			'/// <summary>',
			'/// Which flags each subcommand accepts, GENERATED by',
			'/// tools/parity/generate_cli_options.py from the real Python CLI\'s --help output.',
			'///',
			'/// Captured from --help rather than derived from the argparse source: a regex over',
			'/// program.py missed every option declaring a short alias first, and it also cannot',
			'/// see processor options, which each processor registers itself. --help is the same',
			'/// surface the user sees, so it cannot disagree with the tool.',
			'/// </summary>',
			'public static class CliCommands',
			'{',
			'    public static readonly IReadOnlyDictionary<string, IReadOnlyList<string>> FlagsByCommand =',
			'        new Dictionary<string, IReadOnlyList<string>>(StringComparer.Ordinal)',
			'        {'
		]

		for command in sorted(flags_by_command):
			flags = ', '.join('"%s"' % flag for flag in flags_by_command[command])
			lines.append('            ["%s"] = new[] { %s },' % (command, flags))

		lines[-1] = lines[-1].rstrip(',')
		lines.append('        };')
		lines.append('}')
		open('src/FaceFusion.Cli/CliCommands.cs', 'w').write('\n'.join(lines) + '\n')
		print('generated', len(flags_by_command), 'command flag sets')

	print('generated', len(rows), 'options')


if __name__ == '__main__':
	main()
